/**
 * Created by Peter Cervienka on 12.11.2014.
 */

var areaList = [
    {key: "SR", label: "Slovensko"},
    {key: "E", label: "Európa"},
    {key: "S", label: "Svet"}
];

var countryList = [
    { key: 4, label: 'Afganistan', area: 'S', areaName: 'Svet', default: false },
    { key: 248, label: 'Alandy', area: 'E', areaName: 'Európa', default: false },
    { key: 8, label: 'Albánsko', area: 'E', areaName: 'Európa', default: false },
    { key: 12, label: 'Alžírsko', area: 'E', areaName: 'Európa', default: false },
    { key: 16, label: 'Americká Samoa', area: 'S', areaName: 'Svet', default: false },
    { key: 20, label: 'Andorra', area: 'E', areaName: 'Európa', default: false },
    { key: 24, label: 'Angola', area: 'S', areaName: 'Svet', default: false },
    { key: 660, label: 'Anguilla', area: 'S', areaName: 'Svet', default: false },
    { key: 10, label: 'Antarktída', area: 'S', areaName: 'Svet', default: false },
    { key: 28, label: 'Antigua a Barbuda', area: 'S', areaName: 'Svet', default: false },
    { key: 32, label: 'Argentína', area: 'S', areaName: 'Svet', default: false },
    { key: 51, label: 'Arménsko', area: 'E', areaName: 'Európa', default: false },
    { key: 533, label: 'Aruba', area: 'S', areaName: 'Svet', default: false },
    { key: 36, label: 'Austrália', area: 'S', areaName: 'Svet', default: false },
    { key: 31, label: 'Azerbajdžan', area: 'E', areaName: 'Európa', default: false },
    { key: 44, label: 'Bahamy', area: 'S', areaName: 'Svet', default: false },
    { key: 48, label: 'Bahrajn', area: 'S', areaName: 'Svet', default: false },
    { key: 50, label: 'Bangladéš', area: 'S', areaName: 'Svet', default: false },
    { key: 52, label: 'Barbados', area: 'S', areaName: 'Svet', default: false },
    { key: 56, label: 'Belgicko', area: 'E', areaName: 'Európa', default: false },
    { key: 84, label: 'Belize', area: 'S', areaName: 'Svet', default: false },
    { key: 204, label: 'Benin', area: 'S', areaName: 'Svet', default: false },
    { key: 60, label: 'Bermudy', area: 'S', areaName: 'Svet', default: false },
    { key: 64, label: 'Bhután', area: 'S', areaName: 'Svet', default: false },
    { key: 112, label: 'Bielorusko', area: 'E', areaName: 'Európa', default: false },
    { key: 68, label: 'Bolívia', area: 'S', areaName: 'Svet', default: false },
    { key: 70, label: 'Bosna a Hercegovina', area: 'E', areaName: 'Európa', default: false },
    { key: 72, label: 'Botswana', area: 'S', areaName: 'Svet', default: false },
    { key: 74, label: 'Bouvetov ostrov', area: 'S', areaName: 'Svet', default: false },
    { key: 76, label: 'Brazília', area: 'S', areaName: 'Svet', default: false },
    { key: 86, label: 'Britské indickooceánske územie', area: 'S', areaName: 'Svet', default: false },
    { key: 92, label: 'Britské Panenské ostrovy', area: 'S', areaName: 'Svet', default: false },
    { key: 96, label: 'Brunej', area: 'S', areaName: 'Svet', default: false },
    { key: 100, label: 'Bulharsko', area: 'E', areaName: 'Európa', default: false },
    { key: 854, label: 'Burkina Faso', area: 'S', areaName: 'Svet', default: false },
    { key: 108, label: 'Burundi', area: 'S', areaName: 'Svet', default: false },
    { key: 184, label: 'Cookove ostrovy', area: 'S', areaName: 'Svet', default: false },
    { key: 196, label: 'Cyprus', area: 'E', areaName: 'Európa', default: false },
    { key: 148, label: 'Čad', area: 'S', areaName: 'Svet', default: false },
    { key: 203, label: 'Česká republika', area: 'E', areaName: 'Európa', default: true },
    { key: 499, label: 'Čierna Hora', area: 'E', areaName: 'Európa', default: false },
    { key: 156, label: 'Čína', area: 'S', areaName: 'Svet', default: false },
    { key: 208, label: 'Dánsko', area: 'E', areaName: 'Európa', default: false },
    { key: 180, label: 'Kongo (bývalý Zair)', area: 'S', areaName: 'Svet', default: false },
    { key: 212, label: 'Dominika', area: 'S', areaName: 'Svet', default: false },
    { key: 214, label: 'Dominikánska republika', area: 'S', areaName: 'Svet', default: false },
    { key: 262, label: 'Džibutsko', area: 'S', areaName: 'Svet', default: false },
    { key: 818, label: 'Egypt', area: 'E', areaName: 'Európa', default: false },
    { key: 218, label: 'Ekvádor', area: 'S', areaName: 'Svet', default: false },
    { key: 232, label: 'Eritrea', area: 'S', areaName: 'Svet', default: false },
    { key: 233, label: 'Estónsko', area: 'E', areaName: 'Európa', default: false },
    { key: 231, label: 'Etiópia', area: 'S', areaName: 'Svet', default: false },
    { key: 1003, label: 'Európa', area: 'E', areaName: 'Európa', default: false },
    { key: 234, label: 'Faerské ostrovy', area: 'E', areaName: 'Európa', default: false },
    { key: 238, label: 'Falklandy - Malvíny', area: 'S', areaName: 'Svet', default: false },
    { key: 242, label: 'Fidži', area: 'S', areaName: 'Svet', default: false },
    { key: 608, label: 'Filipíny', area: 'S', areaName: 'Svet', default: false },
    { key: 246, label: 'Fínsko', area: 'E', areaName: 'Európa', default: false },
    { key: 254, label: 'Francúzska Guyana', area: 'S', areaName: 'Svet', default: false },
    { key: 258, label: 'Francúzska Polynézia', area: 'S', areaName: 'Svet', default: false },
    { key: 260, label: 'Francúzske južné územia', area: 'S', areaName: 'Svet', default: false },
    { key: 250, label: 'Francúzsko', area: 'E', areaName: 'Európa', default: true },
    { key: 266, label: 'Gabon', area: 'S', areaName: 'Svet', default: false },
    { key: 270, label: 'Gambia', area: 'S', areaName: 'Svet', default: false },
    { key: 288, label: 'Ghana', area: 'S', areaName: 'Svet', default: false },
    { key: 292, label: 'Gibraltár', area: 'E', areaName: 'Európa', default: false },
    { key: 300, label: 'Grécko', area: 'E', areaName: 'Európa', default: false },
    { key: 308, label: 'Grenada', area: 'S', areaName: 'Svet', default: false },
    { key: 304, label: 'Grónsko', area: 'S', areaName: 'Svet', default: false },
    { key: 268, label: 'Gruzínsko', area: 'E', areaName: 'Európa', default: false },
    { key: 312, label: 'Guadeloupe', area: 'S', areaName: 'Svet', default: false },
    { key: 316, label: 'Guam', area: 'S', areaName: 'Svet', default: false },
    { key: 320, label: 'Guatemala', area: 'S', areaName: 'Svet', default: false },
    { key: 831, label: 'Guernsey', area: 'E', areaName: 'Európa', default: false },
    { key: 324, label: 'Guinea', area: 'S', areaName: 'Svet', default: false },
    { key: 624, label: 'Guinea-Bissau', area: 'S', areaName: 'Svet', default: false },
    { key: 328, label: 'Guyana', area: 'S', areaName: 'Svet', default: false },
    { key: 332, label: 'Haiti', area: 'S', areaName: 'Svet', default: false },
    { key: 334, label: 'Heardov ostrov', area: 'S', areaName: 'Svet', default: false },
    { key: 530, label: 'Holandské Antily', area: 'S', areaName: 'Svet', default: false },
    { key: 528, label: 'Holandsko', area: 'E', areaName: 'Európa', default: false },
    { key: 340, label: 'Honduras', area: 'S', areaName: 'Svet', default: false },
    { key: 344, label: 'Hongkong', area: 'S', areaName: 'Svet', default: false },
    { key: 152, label: 'Čile', area: 'S', areaName: 'Svet', default: false },
    { key: 191, label: 'Chorvátsko', area: 'E', areaName: 'Európa', default: true },
    { key: 356, label: 'India', area: 'S', areaName: 'Svet', default: false },
    { key: 360, label: 'Indonézia', area: 'S', areaName: 'Svet', default: false },
    { key: 368, label: 'Irak', area: 'S', areaName: 'Svet', default: false },
    { key: 364, label: 'Irán', area: 'S', areaName: 'Svet', default: false },
    { key: 372, label: 'Írsko', area: 'E', areaName: 'Európa', default: false },
    { key: 352, label: 'Island', area: 'E', areaName: 'Európa', default: false },
    { key: 376, label: 'Izrael', area: 'E', areaName: 'Európa', default: false },
    { key: 388, label: 'Jamajka', area: 'S', areaName: 'Svet', default: false },
    { key: 392, label: 'Japonsko', area: 'S', areaName: 'Svet', default: false },
    { key: 887, label: 'Jemen', area: 'S', areaName: 'Svet', default: false },
    { key: 832, label: 'Jernsey', area: 'E', areaName: 'Európa', default: false },
    { key: 400, label: 'Jordánsko', area: 'E', areaName: 'Európa', default: false },
    { key: 239, label: 'Južná Georgia a Južné Sandwichove ostrovy', area: 'S', areaName: 'Svet', default: false },
    { key: 710, label: 'Juhoafrická republika', area: 'S', areaName: 'Svet', default: false },
    { key: 410, label: 'Južná Kórea', area: 'S', areaName: 'Svet', default: false },
    { key: 136, label: 'Kajmanie ostrovy', area: 'S', areaName: 'Svet', default: false },
    { key: 116, label: 'Kambodža', area: 'S', areaName: 'Svet', default: false },
    { key: 120, label: 'Kamerun', area: 'S', areaName: 'Svet', default: false },
    { key: 124, label: 'Kanada', area: 'S', areaName: 'Svet', default: false },
    { key: 132, label: 'Kapverdy', area: 'S', areaName: 'Svet', default: false },
    { key: 634, label: 'Katar', area: 'S', areaName: 'Svet', default: false },
    { key: 398, label: 'Kazachstan', area: 'S', areaName: 'Svet', default: false },
    { key: 404, label: 'Keňa', area: 'S', areaName: 'Svet', default: false },
    { key: 417, label: 'Kirgizsko', area: 'S', areaName: 'Svet', default: false },
    { key: 296, label: 'Kiribati', area: 'S', areaName: 'Svet', default: false },
    { key: 166, label: 'Kokosové ostrovy', area: 'S', areaName: 'Svet', default: false },
    { key: 170, label: 'Kolumbia', area: 'S', areaName: 'Svet', default: false },
    { key: 174, label: 'Komory', area: 'S', areaName: 'Svet', default: false },
    { key: 178, label: 'Kongo', area: 'S', areaName: 'Svet', default: false },
    { key: 188, label: 'Kostarika', area: 'S', areaName: 'Svet', default: false },
    { key: 192, label: 'Kuba', area: 'S', areaName: 'Svet', default: false },
    { key: 414, label: 'Kuvajt', area: 'S', areaName: 'Svet', default: false },
    { key: 418, label: 'Laos', area: 'S', areaName: 'Svet', default: false },
    { key: 426, label: 'Lesotho', area: 'S', areaName: 'Svet', default: false },
    { key: 422, label: 'Libanon', area: 'S', areaName: 'Svet', default: false },
    { key: 430, label: 'Libéria', area: 'S', areaName: 'Svet', default: false },
    { key: 434, label: 'Líbya', area: 'S', areaName: 'Svet', default: false },
    { key: 438, label: 'Lichtenštajnsko', area: 'E', areaName: 'Európa', default: false },
    { key: 440, label: 'Litva', area: 'E', areaName: 'Európa', default: false },
    { key: 428, label: 'Lotyšsko', area: 'E', areaName: 'Európa', default: false },
    { key: 442, label: 'Luxembursko', area: 'E', areaName: 'Európa', default: false },
    { key: 446, label: 'Macao', area: 'S', areaName: 'Svet', default: false },
    { key: 807, label: 'Macedónsko', area: 'E', areaName: 'Európa', default: false },
    { key: 450, label: 'Madagaskar', area: 'S', areaName: 'Svet', default: false },
    { key: 348, label: 'Maďarsko', area: 'E', areaName: 'Európa', default: true },
    { key: 458, label: 'Malajzia', area: 'S', areaName: 'Svet', default: false },
    { key: 454, label: 'Malawi', area: 'S', areaName: 'Svet', default: false },
    { key: 462, label: 'Maldivy', area: 'S', areaName: 'Svet', default: false },
    { key: 466, label: 'Mali', area: 'S', areaName: 'Svet', default: false },
    { key: 470, label: 'Malta', area: 'E', areaName: 'Európa', default: false },
    { key: 833, label: 'Man', area: 'E', areaName: 'Európa', default: false },
    { key: 504, label: 'Maroko', area: 'E', areaName: 'Európa', default: false },
    { key: 584, label: 'Marshallove ostrovy', area: 'S', areaName: 'Svet', default: false },
    { key: 474, label: 'Martinik', area: 'S', areaName: 'Svet', default: false },
    { key: 480, label: 'Maurícius', area: 'S', areaName: 'Svet', default: false },
    { key: 478, label: 'Mauritánia', area: 'S', areaName: 'Svet', default: false },
    { key: 175, label: 'Mayotte', area: 'S', areaName: 'Svet', default: false },
    { key: 581, label: 'Menšie odľahlé ostrovy USA', area: 'S', areaName: 'Svet', default: false },
    { key: 249, label: 'Metropolitné Francúzsko', area: 'E', areaName: 'Európa', default: false },
    { key: 484, label: 'Mexiko', area: 'S', areaName: 'Svet', default: false },
    { key: 583, label: 'Mikronézia', area: 'S', areaName: 'Svet', default: false },
    { key: 498, label: 'Moldavsko', area: 'E', areaName: 'Európa', default: false },
    { key: 492, label: 'Monako', area: 'E', areaName: 'Európa', default: false },
    { key: 496, label: 'Mongolsko', area: 'S', areaName: 'Svet', default: false },
    { key: 500, label: 'Montserrat', area: 'S', areaName: 'Svet', default: false },
    { key: 508, label: 'Mozambik', area: 'S', areaName: 'Svet', default: false },
    { key: 104, label: 'Myanmar', area: 'S', areaName: 'Svet', default: false },
    { key: 516, label: 'Namíbia', area: 'S', areaName: 'Svet', default: false },
    { key: 520, label: 'Nauru', area: 'S', areaName: 'Svet', default: false },
    { key: 276, label: 'Nemecko', area: 'E', areaName: 'Európa', default: true },
    { key: 524, label: 'Nepál', area: 'S', areaName: 'Svet', default: false },
    { key: 536, label: 'Neutrálne územia Ruchajmija, Váfra, Andza', area: 'S', areaName: 'Svet', default: false },
    { key: 562, label: 'Niger', area: 'S', areaName: 'Svet', default: false },
    { key: 566, label: 'Nigéria', area: 'S', areaName: 'Svet', default: false },
    { key: 558, label: 'Nikaragua', area: 'S', areaName: 'Svet', default: false },
    { key: 570, label: 'Niue', area: 'S', areaName: 'Svet', default: false },
    { key: 578, label: 'Nórsko', area: 'E', areaName: 'Európa', default: false },
    { key: 540, label: 'Nová Kaledónia', area: 'S', areaName: 'Svet', default: false },
    { key: 554, label: 'Nový Zéland', area: 'S', areaName: 'Svet', default: false },
    { key: 512, label: 'Omán', area: 'S', areaName: 'Svet', default: false },
    { key: 574, label: 'Ostrov Norfolk', area: 'S', areaName: 'Svet', default: false },
    { key: 876, label: 'Ostrovy Wallis a Futuna', area: 'S', areaName: 'Svet', default: false },
    { key: 586, label: 'Pakistan', area: 'S', areaName: 'Svet', default: false },
    { key: 585, label: 'Palau', area: 'S', areaName: 'Svet', default: false },
    { key: 275, label: 'Palestína', area: 'S', areaName: 'Svet', default: false },
    { key: 591, label: 'Panama', area: 'S', areaName: 'Svet', default: false },
    { key: 850, label: 'Americké panenské ostrovy', area: 'S', areaName: 'Svet', default: false },
    { key: 598, label: 'Papua ­ Nová Guinea', area: 'S', areaName: 'Svet', default: false },
    { key: 600, label: 'Paraguaj', area: 'S', areaName: 'Svet', default: false },
    { key: 604, label: 'Peru', area: 'S', areaName: 'Svet', default: false },
    { key: 612, label: 'Pitcairnove ostrovy', area: 'S', areaName: 'Svet', default: false },
    { key: 384, label: 'Pobrežie Slonoviny', area: 'S', areaName: 'Svet', default: false },
    { key: 616, label: 'Poľsko', area: 'E', areaName: 'Európa', default: false },
    { key: 630, label: 'Portoriko', area: 'S', areaName: 'Svet', default: false },
    { key: 620, label: 'Portugalsko', area: 'E', areaName: 'Európa', default: false },
    { key: 40, label: 'Rakúsko', area: 'E', areaName: 'Európa', default: true },
    { key: 638, label: 'Réunion', area: 'S', areaName: 'Svet', default: false },
    { key: 226, label: 'Rovníková Guinea', area: 'S', areaName: 'Svet', default: false },
    { key: 642, label: 'Rumunsko', area: 'E', areaName: 'Európa', default: false },
    { key: 1005, label: 'Rusko - ázijská časť', area: 'S', areaName: 'Svet', default: false },
    { key: 1004, label: 'Rusko - európska časť', area: 'E', areaName: 'Európa', default: false },
    { key: 646, label: 'Rwanda', area: 'S', areaName: 'Svet', default: false },
    { key: 666, label: 'Saint Pierre a Miquelon', area: 'S', areaName: 'Svet', default: false },
    { key: 222, label: 'Salvádor', area: 'S', areaName: 'Svet', default: false },
    { key: 674, label: 'San Maríno', area: 'E', areaName: 'Európa', default: false },
    { key: 682, label: 'Saudská Arábia', area: 'S', areaName: 'Svet', default: false },
    { key: 686, label: 'Senegal', area: 'S', areaName: 'Svet', default: false },
    { key: 408, label: 'Severná Kórea', area: 'S', areaName: 'Svet', default: false },
    { key: 580, label: 'Severné Mariány', area: 'S', areaName: 'Svet', default: false },
    { key: 690, label: 'Seychely', area: 'S', areaName: 'Svet', default: false },
    { key: 694, label: 'Sierra Leone', area: 'S', areaName: 'Svet', default: false },
    { key: 702, label: 'Singapur', area: 'S', areaName: 'Svet', default: false },
    { key: 703, label: 'Slovensko', area: 'SK', areaName: 'Slovensko', default: true },
    { key: 705, label: 'Slovinsko', area: 'E', areaName: 'Európa', default: false },
    { key: 706, label: 'Somálsko', area: 'S', areaName: 'Svet', default: false },
    { key: 784, label: 'Spojené arabské emiráty', area: 'S', areaName: 'Svet', default: false },
    { key: 826, label: 'Veľká Británia', area: 'E', areaName: 'Európa', default: true },
    { key: 840, label: 'Spojené štáty americké', area: 'S', areaName: 'Svet', default: true },
    { key: 688, label: 'Srbsko', area: 'E', areaName: 'Európa', default: false },
    { key: 891, label: 'Srbsko a Čierna hora', area: 'E', areaName: 'Európa', default: false },
    { key: 144, label: 'Srí Lanka', area: 'S', areaName: 'Svet', default: false },
    { key: 140, label: 'Stredoafrická republika', area: 'S', areaName: 'Svet', default: false },
    { key: 736, label: 'Sudán', area: 'S', areaName: 'Svet', default: false },
    { key: 740, label: 'Surinam', area: 'S', areaName: 'Svet', default: false },
    { key: 678, label: 'Svätý Tomáš a Princov ostrov', area: 'S', areaName: 'Svet', default: false },
    { key: 744, label: 'Svalbard a Jan Mayen', area: 'S', areaName: 'Svet', default: false },
    { key: 748, label: 'Svazijsko', area: 'S', areaName: 'Svet', default: false },
    { key: 654, label: 'Svätá Helena', area: 'S', areaName: 'Svet', default: false },
    { key: 662, label: 'Svätá Lucia', area: 'S', areaName: 'Svet', default: false },
    { key: 659, label: 'Svätý Krištof', area: 'S', areaName: 'Svet', default: false },
    { key: 670, label: 'Svätý Vincent a Grenadiny', area: 'S', areaName: 'Svet', default: false },
    { key: 1002, label: 'Svet', area: 'S', areaName: 'Svet', default: false },
    { key: 760, label: 'Sýria', area: 'S', areaName: 'Svet', default: false },
    { key: 90, label: 'Šalamúnove ostrovy', area: 'S', areaName: 'Svet', default: false },
    { key: 724, label: 'Španielsko', area: 'E', areaName: 'Európa', default: true },
    { key: 756, label: 'Švajčiarsko', area: 'E', areaName: 'Európa', default: false },
    { key: 752, label: 'Švédsko', area: 'E', areaName: 'Európa', default: false },
    { key: 762, label: 'Tadžikistan', area: 'S', areaName: 'Svet', default: false },
    { key: 380, label: 'Taliansko', area: 'E', areaName: 'Európa', default: true },
    { key: 834, label: 'Tanzánia', area: 'S', areaName: 'Svet', default: false },
    { key: 764, label: 'Thajsko', area: 'S', areaName: 'Svet', default: false },
    { key: 158, label: 'Taiwan', area: 'S', areaName: 'Svet', default: false },
    { key: 768, label: 'Togo', area: 'S', areaName: 'Svet', default: false },
    { key: 772, label: 'Tokelau', area: 'S', areaName: 'Svet', default: false },
    { key: 776, label: 'Tonga', area: 'S', areaName: 'Svet', default: false },
    { key: 780, label: 'Trinidad a Tobago', area: 'S', areaName: 'Svet', default: false },
    { key: 788, label: 'Tunisko', area: 'E', areaName: 'Európa', default: false },
    { key: 792, label: 'Turecko', area: 'E', areaName: 'Európa', default: false },
    { key: 795, label: 'Turkménsko', area: 'S', areaName: 'Svet', default: false },
    { key: 796, label: 'Turks a Caicos', area: 'S', areaName: 'Svet', default: false },
    { key: 798, label: 'Tuvalu', area: 'S', areaName: 'Svet', default: false },
    { key: 800, label: 'Uganda', area: 'S', areaName: 'Svet', default: false },
    { key: 804, label: 'Ukrajina', area: 'E', areaName: 'Európa', default: false },
    { key: 858, label: 'Uruguaj', area: 'S', areaName: 'Svet', default: false },
    { key: 860, label: 'Uzbekistan', area: 'S', areaName: 'Svet', default: false },
    { key: 548, label: 'Vanuatu', area: 'S', areaName: 'Svet', default: false },
    { key: 336, label: 'Vatikán', area: 'E', areaName: 'Európa', default: false },
    { key: 862, label: 'Venezuela', area: 'S', areaName: 'Svet', default: false },
    { key: 162, label: 'Vianočný ostrov', area: 'S', areaName: 'Svet', default: false },
    { key: 704, label: 'Vietnam', area: 'S', areaName: 'Svet', default: false },
    { key: 626, label: 'Východný Timor', area: 'S', areaName: 'Svet', default: false },
    { key: 894, label: 'Zambia', area: 'S', areaName: 'Svet', default: false },
    { key: 732, label: 'Západná Sahara', area: 'S', areaName: 'Svet', default: false },
    { key: 882, label: 'Západná Samoa', area: 'S', areaName: 'Svet', default: false },
    { key: 716, label: 'Zimbabwe', area: 'S', areaName: 'Svet', default: false },
    { key: 1001, label: 'mimo Európy', area: 'S', areaName: 'Svet', default: false }
];


var getDefaultCountries = function () {
    var result = [];
    if (countryList && countryList.length > 0) {
        for (var i = 0; i < countryList.length; i++) {
            var item = countryList[i];
            if (item.default == true) {
                result.push(item);
            }
        }
    }

    result.push( { key: 0, label: '--------------------------', area: "", default: false } );
    result.push( { key: 1003, label: 'Európa', area: 'E', areaName: 'Európa', default: false } );
    result.push( { key: 1002, label: 'Svet', area: 'S', areaName: 'Svet', default: false } );

    return result;
};

var getAllCountries = function() {
    return countryList;
};

$( document ).ready(function() {
    if (countryList && countryList.length > 0) {
        for (var i = 0; i < countryList.length; i++) {
            var item = countryList[i];
            item.label = item.label + " ( " + item.areaName + " )";
        }
    }
});
