<?xml version="1.0" encoding="UTF-8"?>
<!--Designed and generated by Altova StyleVision Enterprise Edition 2013 rel. 2 sp2 (x64) - see http://www.altova.com/stylevision for more information.-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:altova="http://www.altova.com" xmlns:altovaext="http://www.altova.com/xslt-extensions" xmlns:clitype="clitype" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:iso4217="http://www.xbrl.org/2003/iso4217" xmlns:ix="http://www.xbrl.org/2008/inlineXBRL" xmlns:java="java" xmlns:link="http://www.xbrl.org/2003/linkbase" xmlns:sps="http://www.altova.com/StyleVision/user-xpath-functions" xmlns:xbrldi="http://xbrl.org/2006/xbrldi" xmlns:xbrli="http://www.xbrl.org/2003/instance" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:fo="http://www.w3.org/1999/XSL/Format" xmlns:svg="http://www.w3.org/2000/svg" exclude-result-prefixes="altova altovaext clitype fn iso4217 ix java link sps xbrldi xbrli xlink xs xsi">
	<xsl:output version="1.0" method="xml" encoding="UTF-8" indent="no"/>
	<xsl:param name="SV_OutputFormat" select="'PDF'"/>
	<xsl:variable name="XML" select="/"/>
	<xsl:decimal-format name="format1" grouping-separator=" " decimal-separator=","/>
	<xsl:variable name="fo:layout-master-set">
		<fo:layout-master-set>
			<fo:simple-page-master master-name="page-master-0-even" margin-left="0.40in" margin-right="0.40in" page-height="11in" page-width="8.50in" margin-top="0.0in" margin-bottom="0.0in">
				<fo:region-body margin-top="0in" margin-bottom="0.20in" column-gap="0.50in"/>
			</fo:simple-page-master>
			<fo:simple-page-master master-name="page-master-0-odd" margin-left="0.40in" margin-right="0.40in" page-height="11in" page-width="8.50in" margin-top="0.0in" margin-bottom="0.0in">
				<fo:region-body margin-top="0in" margin-bottom="0.20in" column-gap="0.50in"/>
			</fo:simple-page-master>
			<fo:simple-page-master master-name="page-master-0-even-first" margin-left="0.40in" margin-right="0.40in" page-height="11in" page-width="8.50in" margin-top="0.0in" margin-bottom="0.0in">
				<fo:region-body margin-top="0in" margin-bottom="0.20in" column-gap="0.50in"/>
				<fo:region-before region-name="even-page-header-first" overflow="hidden" extent="0in"/>
			</fo:simple-page-master>
			<fo:simple-page-master master-name="page-master-0-odd-first" margin-left="0.40in" margin-right="0.40in" page-height="11in" page-width="8.50in" margin-top="0.0in" margin-bottom="0.0in">
				<fo:region-body margin-top="0in" margin-bottom="0.20in" column-gap="0.50in"/>
				<fo:region-before region-name="odd-page-header-first" overflow="hidden" extent="0in"/>
			</fo:simple-page-master>
			<fo:simple-page-master master-name="page-master-0-even-last" margin-left="0.40in" margin-right="0.40in" page-height="11in" page-width="8.50in" margin-top="0.0in" margin-bottom="0.0in">
				<fo:region-body margin-top="0.30in" margin-bottom="0.30in" column-gap="0.50in"/>
				<fo:region-before region-name="even-page-header" overflow="hidden" extent="0.30in"/>
				<fo:region-after region-name="even-page-footer" overflow="hidden" extent="0.30in"/>
			</fo:simple-page-master>
			<fo:simple-page-master master-name="page-master-0-odd-last" margin-left="0.40in" margin-right="0.40in" page-height="11in" page-width="8.50in" margin-top="0.0in" margin-bottom="0.0in">
				<fo:region-body margin-top="0.30in" margin-bottom="0.30in" column-gap="0.50in"/>
				<fo:region-before region-name="odd-page-header" overflow="hidden" extent="0.30in"/>
				<fo:region-after region-name="odd-page-footer" overflow="hidden" extent="0.30in"/>
			</fo:simple-page-master>
			<fo:page-sequence-master master-name="page-master-0">
				<fo:repeatable-page-master-alternatives>
					<fo:conditional-page-master-reference master-reference="page-master-0-even-first" odd-or-even="even" page-position="first"/>
					<fo:conditional-page-master-reference master-reference="page-master-0-odd-first" odd-or-even="odd" page-position="first"/>
					<fo:conditional-page-master-reference master-reference="page-master-0-even-last" odd-or-even="even" page-position="last"/>
					<fo:conditional-page-master-reference master-reference="page-master-0-odd-last" odd-or-even="odd" page-position="last"/>
					<fo:conditional-page-master-reference master-reference="page-master-0-even" odd-or-even="even"/>
					<fo:conditional-page-master-reference master-reference="page-master-0-odd" odd-or-even="odd"/>
				</fo:repeatable-page-master-alternatives>
			</fo:page-sequence-master>
		</fo:layout-master-set>
	</xsl:variable>
	<xsl:variable name="altova:nPxPerIn" select="96"/>
	<xsl:template match="/">
		<fo:root>
			<xsl:copy-of select="$fo:layout-master-set"/>
			<fo:declarations>
				<x:xmpmeta xmlns:x="adobe:ns:meta/">
					<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
						<rdf:Description rdf:about="" xmlns:xmp="http://ns.adobe.com/xap/1.0/">
							<xmp:CreatorTool>Altova StyleVision Enterprise Edition 2013 rel. 2 sp2 (x64) (http://www.altova.com)</xmp:CreatorTool>
						</rdf:Description>
					</rdf:RDF>
				</x:xmpmeta>
			</fo:declarations>
			<fo:page-sequence force-page-count="no-force" master-reference="page-master-0" initial-page-number="auto" format="1">
				<fo:static-content flow-name="odd-page-header-first">
					<fo:block-container overflow="hidden" display-align="before">
						<fo:block font-family="Arial" font-size="12px"/>
					</fo:block-container>
				</fo:static-content>
				<fo:static-content flow-name="even-page-header-first">
					<fo:block-container overflow="hidden" display-align="before">
						<fo:block font-family="Arial" font-size="12px"/>
					</fo:block-container>
				</fo:static-content>
				<fo:flow flow-name="xsl-region-body">
					<fo:block font-family="Arial" font-size="12px" font-weight="normal">
						<xsl:for-each select="$XML">
							<xsl:for-each select="agreement">
								<fo:inline-container>
									<fo:block>
										<xsl:text>&#x200B;</xsl:text>
									</fo:block>
								</fo:inline-container>
								<fo:table color="#B5B5B5" font-size="0.13in" line-height="normal" padding-top="0.31in" width="100%" table-layout="fixed" border-spacing="0">
									<fo:table-column column-width="30%"/>
									<fo:table-column column-width="28%"/>
									<fo:table-column column-width="40%"/>
									<xsl:variable name="altova:CurrContextGrid_1" select="."/>
									<fo:table-body start-indent="0pt">
										<xsl:variable name="altova:tablerows">
											<fo:table-row line-height="normal">
												<fo:table-cell font-size="0.13in" padding="0" padding-top="0.31in" display-align="center">
													<fo:block-container overflow="hidden">
														<fo:block text-align="left">
															<fo:external-graphic text-align="right" display-align="after" content-width="2.08in" scaling="non-uniform">
																<xsl:attribute name="src">
																	<xsl:text>url(</xsl:text>
																	<xsl:call-template name="altova:double-backslash">
																		<xsl:with-param name="text">
																			<xsl:value-of select="string(&apos;pdf_logo.jpg&apos;)"/>
																		</xsl:with-param>
																		<xsl:with-param name="text-length">
																			<xsl:value-of select="string-length(string(&apos;pdf_logo.jpg&apos;))"/>
																		</xsl:with-param>
																	</xsl:call-template>
																	<xsl:text>)</xsl:text>
																</xsl:attribute>
															</fo:external-graphic>
															<fo:inline>
																<xsl:text>&#x200B;</xsl:text>
															</fo:inline>
														</fo:block>
													</fo:block-container>
												</fo:table-cell>
												<fo:table-cell border-left="0.01in solid #B5B5B5" line-height="normal" padding-left="0.10in" padding-top="0.42in" padding="0" display-align="center">
													<fo:block-container overflow="hidden">
														<fo:block text-align="left">
															<fo:inline>
																<xsl:text>Union poistovňa, a.s.</xsl:text>
															</fo:inline>
															<fo:block/>
															<fo:inline>
																<xsl:text>Bajkalská 29/A</xsl:text>
															</fo:inline>
															<fo:block/>
															<fo:inline>
																<xsl:text>813 60 Bratislava</xsl:text>
															</fo:inline>
															<fo:block/>
															<fo:inline>
																<xsl:text>IČO: 31322051</xsl:text>
															</fo:inline>
															<fo:block/>
															<fo:inline>
																<xsl:text>DIČ: 2020800353</xsl:text>
															</fo:inline>
														</fo:block>
													</fo:block-container>
												</fo:table-cell>
												<fo:table-cell font-size="0.13in" line-height="normal" padding="0" padding-top="0" display-align="before">
													<fo:block-container overflow="hidden">
														<fo:block text-align="left">
															<fo:inline-container>
																<fo:block>
																	<xsl:text>&#x200B;</xsl:text>
																</fo:block>
															</fo:inline-container>
															<fo:block border-left="0.01in solid #B5B5B5" line-height="normal" padding-left="0.10in" padding-top="0.42in" margin-right="100% - 100%" space-before="0" space-after="0" margin="0pt">
																<fo:inline font-size="0.13in" line-height="normal" text-align="left">
																	<xsl:text>Spoločnosť zapísana v Obchodnom registri</xsl:text>
																</fo:inline>
																<fo:block/>
																<fo:inline font-size="0.13in" text-align="left">
																	<xsl:text>Okresného súdu Bratislava I, odd. Sa, vl. č. 383/B</xsl:text>
																</fo:inline>
															</fo:block>
														</fo:block>
													</fo:block-container>
												</fo:table-cell>
											</fo:table-row>
										</xsl:variable>
										<xsl:choose>
											<xsl:when test="string($altova:tablerows)">
												<xsl:copy-of select="$altova:tablerows"/>
											</xsl:when>
											<xsl:otherwise>
												<fo:table-row>
													<fo:table-cell>
														<fo:block/>
													</fo:table-cell>
												</fo:table-row>
											</xsl:otherwise>
										</xsl:choose>
									</fo:table-body>
								</fo:table>
								<fo:inline-container>
									<fo:block>
										<xsl:text>&#x200B;</xsl:text>
									</fo:block>
								</fo:inline-container>
								<fo:block color="#D8002C" margin="0.00in" text-align="center" margin-right="0.00in + 100% - 100%" font-weight="bold" space-before="1.12em" space-after="1.12em">
									<fo:inline>
										<xsl:text>POŽIADAVKA NA PLATBU POISTNÉHO</xsl:text>
									</fo:inline>
								</fo:block>
								<fo:inline font-size="0.13in">
									<xsl:text>na základe poistnej zmluvy č. </xsl:text>
								</fo:inline>
								<xsl:for-each select="variableSymbol">
									<xsl:variable name="value-of-template_2">
										<xsl:apply-templates/>
									</xsl:variable>
									<xsl:choose>
										<xsl:when test="contains(string($value-of-template_2),'&#x200B;')">
											<fo:block font-size="0.13in">
												<xsl:copy-of select="$value-of-template_2"/>
											</fo:block>
										</xsl:when>
										<xsl:otherwise>
											<fo:inline font-size="0.13in">
												<xsl:copy-of select="$value-of-template_2"/>
											</fo:inline>
										</xsl:otherwise>
									</xsl:choose>
								</xsl:for-each>
								<fo:inline font-size="0.13in">
									<xsl:text> o komplexnom cestovnom poistení pre účastníkov zájazdu Vás týmto žiadame o úhradu poistného: </xsl:text>
								</fo:inline>
								<fo:block/>
								<fo:block>
									<fo:leader leader-pattern="space"/>
								</fo:block>
								<fo:inline-container>
									<fo:block>
										<xsl:text>&#x200B;</xsl:text>
									</fo:block>
								</fo:inline-container>
								<fo:table font-size="0.13in" table-layout="fixed" width="100%" border-spacing="0">
									<fo:table-column column-width="50%"/>
									<fo:table-column column-width="50%"/>
									<xsl:variable name="altova:CurrContextGrid_3" select="."/>
									<fo:table-body start-indent="0pt">
										<xsl:variable name="altova:tablerows">
											<fo:table-row>
												<fo:table-cell padding-bottom="0.01in" padding-top="0.01in" padding="0" display-align="center">
													<fo:block-container overflow="hidden">
														<fo:block text-align="left">
															<fo:inline>
																<xsl:text>SUMA na úhradu</xsl:text>
															</fo:inline>
														</fo:block>
													</fo:block-container>
												</fo:table-cell>
												<fo:table-cell padding-bottom="0.01in" padding-top="0.01in" padding="0" display-align="center">
													<fo:block-container overflow="hidden">
														<fo:block text-align="left">
															<xsl:for-each select="poistneSuma">
																<xsl:variable name="value-of-template_4">
																	<xsl:apply-templates/>
																</xsl:variable>
																<xsl:choose>
																	<xsl:when test="contains(string($value-of-template_4),'&#x200B;')">
																		<fo:block>
																			<xsl:copy-of select="$value-of-template_4"/>
																		</fo:block>
																	</xsl:when>
																	<xsl:otherwise>
																		<fo:inline>
																			<xsl:copy-of select="$value-of-template_4"/>
																		</fo:inline>
																	</xsl:otherwise>
																</xsl:choose>
															</xsl:for-each>
															<fo:inline>
																<xsl:text> Eur</xsl:text>
															</fo:inline>
														</fo:block>
													</fo:block-container>
												</fo:table-cell>
											</fo:table-row>
											<fo:table-row>
												<fo:table-cell padding-bottom="0.01in" padding-top="0.01in" padding="0" display-align="before">
													<fo:block-container overflow="hidden">
														<fo:block text-align="left">
															<fo:inline>
																<xsl:text>účet číslo </xsl:text>
															</fo:inline>
														</fo:block>
													</fo:block-container>
												</fo:table-cell>
												<fo:table-cell padding-bottom="0.01in" padding-top="0.01in" padding="0" display-align="before">
													<fo:block-container overflow="hidden">
														<fo:block text-align="left">
															<fo:inline>
																<xsl:text>6600547090/1111, IBAN SK59 1111 0000 0066 0054 7090, BIC UNCRSKBX</xsl:text>
															</fo:inline>
															<fo:block/>
														</fo:block>
													</fo:block-container>
												</fo:table-cell>
											</fo:table-row>
											<fo:table-row>
												<fo:table-cell padding-bottom="0.01in" padding-top="0.01in" padding="0" display-align="before">
													<fo:block-container overflow="hidden">
														<fo:block text-align="left">
															<fo:inline>
																<xsl:text>banka 	</xsl:text>
															</fo:inline>
														</fo:block>
													</fo:block-container>
												</fo:table-cell>
												<fo:table-cell padding-bottom="0.01in" padding-top="0.01in" padding="0" display-align="before">
													<fo:block-container overflow="hidden">
														<fo:block text-align="left">
															<fo:inline>
																<xsl:text>UniCredit Bank Czech Republic and Slovakia, a.s., organizačná zložka: UniCredit Bank Czech Republic and Slovakia, a.s., pobočka zahraničnej banky</xsl:text>
															</fo:inline>
														</fo:block>
													</fo:block-container>
												</fo:table-cell>
											</fo:table-row>
											<fo:table-row>
												<fo:table-cell padding-bottom="0.01in" padding-top="0.01in" padding="0" display-align="before">
													<fo:block-container overflow="hidden">
														<fo:block text-align="left">
															<fo:inline font-weight="normal">
																<xsl:text>variabilný symbol</xsl:text>
															</fo:inline>
														</fo:block>
													</fo:block-container>
												</fo:table-cell>
												<fo:table-cell padding-bottom="0.01in" padding-top="0.01in" padding="0" display-align="before">
													<fo:block-container overflow="hidden">
														<fo:block text-align="left">
															<xsl:for-each select="variableSymbol">
																<xsl:variable name="value-of-template_5">
																	<xsl:apply-templates/>
																</xsl:variable>
																<xsl:choose>
																	<xsl:when test="contains(string($value-of-template_5),'&#x200B;')">
																		<fo:block font-size="0.13in">
																			<xsl:copy-of select="$value-of-template_5"/>
																		</fo:block>
																	</xsl:when>
																	<xsl:otherwise>
																		<fo:inline font-size="0.13in">
																			<xsl:copy-of select="$value-of-template_5"/>
																		</fo:inline>
																	</xsl:otherwise>
																</xsl:choose>
															</xsl:for-each>
														</fo:block>
													</fo:block-container>
												</fo:table-cell>
											</fo:table-row>
											<fo:table-row>
												<fo:table-cell padding-bottom="0.01in" padding-top="0.01in" padding="0" display-align="before">
													<fo:block-container overflow="hidden">
														<fo:block text-align="left">
															<fo:inline>
																<xsl:text>konštantný symbol</xsl:text>
															</fo:inline>
														</fo:block>
													</fo:block-container>
												</fo:table-cell>
												<fo:table-cell padding-bottom="0.01in" padding-top="0.01in" padding="0" display-align="before">
													<fo:block-container overflow="hidden">
														<fo:block text-align="left">
															<fo:inline>
																<xsl:text>3558</xsl:text>
															</fo:inline>
														</fo:block>
													</fo:block-container>
												</fo:table-cell>
											</fo:table-row>
											<fo:table-row>
												<fo:table-cell padding-bottom="0.01in" padding-top="0.01in" padding="0" display-align="before">
													<fo:block-container overflow="hidden">
														<fo:block text-align="left">
															<fo:inline>
																<xsl:text>dátum vystavenia požiadavky na platbu</xsl:text>
															</fo:inline>
														</fo:block>
													</fo:block-container>
												</fo:table-cell>
												<fo:table-cell padding-bottom="0.01in" padding-top="0.01in" padding="0" display-align="after">
													<fo:block-container overflow="hidden">
														<fo:block text-align="left">
															<xsl:for-each select="dateOfSigning">
																<fo:inline font-size="0.13in">
																	<xsl:value-of select="format-number(number(substring(string(string(.)), 9, 2)), '00', 'format1')"/>
																	<xsl:text>.</xsl:text>
																	<xsl:value-of select="format-number(number(substring(string(string(.)), 6, 2)), '00', 'format1')"/>
																	<xsl:text>.</xsl:text>
																	<xsl:value-of select="format-number(number(substring(string(string(string(.))), 1, 4)), '0000', 'format1')"/>
																</fo:inline>
															</xsl:for-each>
														</fo:block>
													</fo:block-container>
												</fo:table-cell>
											</fo:table-row>
											<fo:table-row>
												<fo:table-cell padding-bottom="0.01in" padding-top="0.01in" padding="0" display-align="before">
													<fo:block-container overflow="hidden">
														<fo:block text-align="left">
															<fo:inline>
																<xsl:text>dátum splatnosti</xsl:text>
															</fo:inline>
														</fo:block>
													</fo:block-container>
												</fo:table-cell>
												<fo:table-cell padding-bottom="0.01in" padding-top="0.01in" padding="0" display-align="before">
													<fo:block-container overflow="hidden">
														<fo:block text-align="left">
															<xsl:for-each select="insuredFrom">
																<fo:inline>
																	<xsl:value-of select="format-number(number(substring(string(string(.)), 9, 2)), '00', 'format1')"/>
																	<xsl:text>.</xsl:text>
																	<xsl:value-of select="format-number(number(substring(string(string(.)), 6, 2)), '00', 'format1')"/>
																	<xsl:text>.</xsl:text>
																	<xsl:value-of select="format-number(number(substring(string(string(string(.))), 1, 4)), '0000', 'format1')"/>
																</fo:inline>
															</xsl:for-each>
														</fo:block>
													</fo:block-container>
												</fo:table-cell>
											</fo:table-row>
											<fo:table-row>
												<fo:table-cell padding-bottom="0.01in" padding-top="0.01in" padding="0" display-align="center">
													<fo:block-container overflow="hidden">
														<fo:block text-align="left"/>
													</fo:block-container>
												</fo:table-cell>
												<fo:table-cell padding-bottom="0.01in" padding-top="0.01in" padding="0" display-align="center">
													<fo:block-container overflow="hidden">
														<fo:block text-align="left"/>
													</fo:block-container>
												</fo:table-cell>
											</fo:table-row>
										</xsl:variable>
										<xsl:choose>
											<xsl:when test="string($altova:tablerows)">
												<xsl:copy-of select="$altova:tablerows"/>
											</xsl:when>
											<xsl:otherwise>
												<fo:table-row>
													<fo:table-cell>
														<fo:block/>
													</fo:table-cell>
												</fo:table-row>
											</xsl:otherwise>
										</xsl:choose>
									</fo:table-body>
								</fo:table>
								<fo:block>
									<fo:leader leader-pattern="space"/>
								</fo:block>
								<fo:inline-container>
									<fo:block>
										<xsl:text>&#x200B;</xsl:text>
									</fo:block>
								</fo:inline-container>
								<fo:table font-size="0.13in" table-layout="fixed" width="100%" border-spacing="0">
									<fo:table-column column-width="100%"/>
									<xsl:variable name="altova:CurrContextGrid_8" select="."/>
									<fo:table-body start-indent="0pt">
										<xsl:variable name="altova:tablerows">
											<fo:table-row>
												<fo:table-cell padding="0" display-align="center">
													<fo:block-container overflow="hidden">
														<fo:block text-align="left">
															<fo:inline font-size="0.13in">
																<xsl:text>Ďakujeme Vám za včasné poukázanie platby.</xsl:text>
															</fo:inline>
															<fo:block/>
															<fo:block>
																<fo:leader leader-pattern="space"/>
															</fo:block>
															<fo:inline font-size="0.13in">
																<xsl:text>S pozdravom</xsl:text>
															</fo:inline>
															<fo:block/>
															<fo:inline-container>
																<fo:block>
																	<xsl:text>&#x200B;</xsl:text>
																</fo:block>
															</fo:inline-container>
															<fo:block font-size="0.13in" margin-left="1.56in" text-align="left" margin-right="100% - 100%" space-before="0" space-after="0" margin="0pt">
																<fo:inline>
																	<xsl:text>Union poisťovňa, a.s.</xsl:text>
																</fo:inline>
															</fo:block>
														</fo:block>
													</fo:block-container>
												</fo:table-cell>
											</fo:table-row>
										</xsl:variable>
										<xsl:choose>
											<xsl:when test="string($altova:tablerows)">
												<xsl:copy-of select="$altova:tablerows"/>
											</xsl:when>
											<xsl:otherwise>
												<fo:table-row>
													<fo:table-cell>
														<fo:block/>
													</fo:table-cell>
												</fo:table-row>
											</xsl:otherwise>
										</xsl:choose>
									</fo:table-body>
								</fo:table>
								<fo:inline>
									<xsl:text>---------------------------------------------------------------------------------------------------------------------------------------</xsl:text>
								</fo:inline>
								<fo:block/>
								<fo:inline-container>
									<fo:block>
										<xsl:text>&#x200B;</xsl:text>
									</fo:block>
								</fo:inline-container>
								<fo:block font-size="0.13in" font-weight="bold" margin="0.00in" padding="0.00in" text-align="left" margin-right="0.00in + 100% - 100%" space-before="0" space-after="0">
									<fo:inline>
										<xsl:text>Príkaz na úhradu</xsl:text>
									</fo:inline>
								</fo:block>
								<fo:inline-container>
									<fo:block>
										<xsl:text>&#x200B;</xsl:text>
									</fo:block>
								</fo:inline-container>
								<fo:table font-size="0.13in" table-layout="fixed" width="100%" border-spacing="5">
									<fo:table-column column-width="50%"/>
									<fo:table-column column-width="50%"/>
									<xsl:variable name="altova:CurrContextGrid_9" select="."/>
									<fo:table-body start-indent="0pt">
										<xsl:variable name="altova:tablerows">
											<fo:table-row>
												<fo:table-cell padding-left="0.00in" padding="5" display-align="center">
													<fo:block-container overflow="hidden">
														<fo:block text-align="left">
															<fo:inline font-size="0.13in" font-weight="bold">
																<xsl:text>Príkazca</xsl:text>
															</fo:inline>
														</fo:block>
													</fo:block-container>
												</fo:table-cell>
												<fo:table-cell padding="5" display-align="center">
													<fo:block-container overflow="hidden">
														<fo:block text-align="left">
															<fo:inline font-size="0.13in" font-weight="bold">
																<xsl:text>Príjemca</xsl:text>
															</fo:inline>
														</fo:block>
													</fo:block-container>
												</fo:table-cell>
											</fo:table-row>
											<fo:table-row>
												<fo:table-cell padding-left="0.00in" padding="5" display-align="before">
													<fo:block-container overflow="hidden">
														<fo:block text-align="left">
															<fo:inline-container>
																<fo:block>
																	<xsl:text>&#x200B;</xsl:text>
																</fo:block>
															</fo:inline-container>
															<fo:table font-family="Arial" table-layout="fixed" width="80%" border-spacing="0">
																<fo:table-column column-width="proportional-column-width(1)"/>
																<fo:table-column column-width="proportional-column-width(1)"/>
																<xsl:variable name="altova:CurrContextGrid_10" select="."/>
																<fo:table-body start-indent="0pt">
																	<xsl:variable name="altova:tablerows">
																		<fo:table-row>
																			<fo:table-cell border="0.01in solid black" padding="5" display-align="center">
																				<fo:block-container overflow="hidden">
																					<fo:block text-align="left">
																						<fo:inline>
																							<xsl:text>číslo účtu</xsl:text>
																						</fo:inline>
																					</fo:block>
																				</fo:block-container>
																			</fo:table-cell>
																			<fo:table-cell border="0.01in solid black" padding="5" display-align="center">
																				<fo:block-container overflow="hidden">
																					<fo:block text-align="left">
																						<fo:inline>
																							<xsl:text>kód banky</xsl:text>
																						</fo:inline>
																					</fo:block>
																				</fo:block-container>
																			</fo:table-cell>
																		</fo:table-row>
																		<fo:table-row>
																			<fo:table-cell border="0.01in solid black" padding="5" display-align="center">
																				<fo:block-container overflow="hidden">
																					<fo:block text-align="left">
																						<fo:block>
																							<fo:leader leader-pattern="space"/>
																						</fo:block>
																					</fo:block>
																				</fo:block-container>
																			</fo:table-cell>
																			<fo:table-cell border="0.01in solid black" padding="5" display-align="center">
																				<fo:block-container overflow="hidden">
																					<fo:block text-align="left">
																						<fo:block>
																							<fo:leader leader-pattern="space"/>
																						</fo:block>
																					</fo:block>
																				</fo:block-container>
																			</fo:table-cell>
																		</fo:table-row>
																	</xsl:variable>
																	<xsl:choose>
																		<xsl:when test="string($altova:tablerows)">
																			<xsl:copy-of select="$altova:tablerows"/>
																		</xsl:when>
																		<xsl:otherwise>
																			<fo:table-row>
																				<fo:table-cell>
																					<fo:block/>
																				</fo:table-cell>
																			</fo:table-row>
																		</xsl:otherwise>
																	</xsl:choose>
																</fo:table-body>
															</fo:table>
														</fo:block>
													</fo:block-container>
												</fo:table-cell>
												<fo:table-cell padding-right="0.00in" padding="5" display-align="before">
													<fo:block-container overflow="hidden">
														<fo:block text-align="left">
															<fo:inline-container>
																<fo:block>
																	<xsl:text>&#x200B;</xsl:text>
																</fo:block>
															</fo:inline-container>
															<fo:table table-layout="fixed" width="100%" border-spacing="0">
																<fo:table-column column-width="proportional-column-width(1)"/>
																<fo:table-column column-width="proportional-column-width(1)"/>
																<xsl:variable name="altova:CurrContextGrid_11" select="."/>
																<fo:table-body start-indent="0pt">
																	<xsl:variable name="altova:tablerows">
																		<fo:table-row>
																			<fo:table-cell border="0.01in solid black" padding="5" display-align="center">
																				<fo:block-container overflow="hidden">
																					<fo:block text-align="left">
																						<fo:inline font-size="0.13in">
																							<xsl:text>číslo účtu</xsl:text>
																						</fo:inline>
																					</fo:block>
																				</fo:block-container>
																			</fo:table-cell>
																			<fo:table-cell border="0.01in solid black" padding="5" display-align="center">
																				<fo:block-container overflow="hidden">
																					<fo:block text-align="left">
																						<fo:inline font-size="0.13in">
																							<xsl:text>kód banky</xsl:text>
																						</fo:inline>
																					</fo:block>
																				</fo:block-container>
																			</fo:table-cell>
																		</fo:table-row>
																		<fo:table-row>
																			<fo:table-cell border="0.01in solid black" padding="5" display-align="center">
																				<fo:block-container overflow="hidden">
																					<fo:block text-align="left">
																						<fo:inline font-size="0.13in" font-weight="bold">
																							<xsl:text>6600547090</xsl:text>
																						</fo:inline>
																					</fo:block>
																				</fo:block-container>
																			</fo:table-cell>
																			<fo:table-cell border="0.01in solid black" padding="5" display-align="center">
																				<fo:block-container overflow="hidden">
																					<fo:block text-align="left">
																						<fo:inline font-size="0.13in" font-weight="bold">
																							<xsl:text>1111</xsl:text>
																						</fo:inline>
																					</fo:block>
																				</fo:block-container>
																			</fo:table-cell>
																		</fo:table-row>
																	</xsl:variable>
																	<xsl:choose>
																		<xsl:when test="string($altova:tablerows)">
																			<xsl:copy-of select="$altova:tablerows"/>
																		</xsl:when>
																		<xsl:otherwise>
																			<fo:table-row>
																				<fo:table-cell>
																					<fo:block/>
																				</fo:table-cell>
																			</fo:table-row>
																		</xsl:otherwise>
																	</xsl:choose>
																</fo:table-body>
															</fo:table>
														</fo:block>
													</fo:block-container>
												</fo:table-cell>
											</fo:table-row>
											<fo:table-row>
												<fo:table-cell padding="5" display-align="center">
													<fo:block-container overflow="hidden">
														<fo:block text-align="left"/>
													</fo:block-container>
												</fo:table-cell>
												<fo:table-cell padding="5" display-align="center">
													<fo:block-container overflow="hidden">
														<fo:block text-align="left">
															<fo:inline font-size="0.13in" font-weight="bold">
																<xsl:text>Symboly platby</xsl:text>
															</fo:inline>
														</fo:block>
													</fo:block-container>
												</fo:table-cell>
											</fo:table-row>
											<fo:table-row>
												<fo:table-cell padding-left="0.00in" padding="5" display-align="before">
													<fo:block-container overflow="hidden">
														<fo:block text-align="left">
															<fo:inline-container>
																<fo:block>
																	<xsl:text>&#x200B;</xsl:text>
																</fo:block>
															</fo:inline-container>
															<fo:table table-layout="fixed" width="80%" border-spacing="0">
																<fo:table-column column-width="proportional-column-width(1)"/>
																<fo:table-column column-width="proportional-column-width(1)"/>
																<fo:table-column column-width="proportional-column-width(1)"/>
																<xsl:variable name="altova:CurrContextGrid_12" select="."/>
																<fo:table-body start-indent="0pt">
																	<xsl:variable name="altova:tablerows">
																		<fo:table-row>
																			<fo:table-cell border="0.01in solid black" padding="5" display-align="center">
																				<fo:block-container overflow="hidden">
																					<fo:block text-align="left">
																						<fo:inline font-size="0.13in">
																							<xsl:text>čiastka</xsl:text>
																						</fo:inline>
																					</fo:block>
																				</fo:block-container>
																			</fo:table-cell>
																			<fo:table-cell border="0.01in solid black" padding="5" display-align="center">
																				<fo:block-container overflow="hidden">
																					<fo:block text-align="left">
																						<fo:inline font-size="0.13in">
																							<xsl:text>mena</xsl:text>
																						</fo:inline>
																					</fo:block>
																				</fo:block-container>
																			</fo:table-cell>
																			<fo:table-cell border="0.01in solid black" padding="5" display-align="center">
																				<fo:block-container overflow="hidden">
																					<fo:block text-align="left">
																						<fo:inline font-size="0.13in">
																							<xsl:text>splatnosť</xsl:text>
																						</fo:inline>
																					</fo:block>
																				</fo:block-container>
																			</fo:table-cell>
																		</fo:table-row>
																		<fo:table-row>
																			<fo:table-cell border="0.01in solid black" padding="5" display-align="center">
																				<fo:block-container overflow="hidden">
																					<fo:block text-align="left">
																						<xsl:for-each select="poistneSuma">
																							<xsl:variable name="value-of-template_13">
																								<xsl:apply-templates/>
																							</xsl:variable>
																							<xsl:choose>
																								<xsl:when test="contains(string($value-of-template_13),'&#x200B;')">
																									<fo:block>
																										<xsl:copy-of select="$value-of-template_13"/>
																									</fo:block>
																								</xsl:when>
																								<xsl:otherwise>
																									<fo:inline>
																										<xsl:copy-of select="$value-of-template_13"/>
																									</fo:inline>
																								</xsl:otherwise>
																							</xsl:choose>
																						</xsl:for-each>
																					</fo:block>
																				</fo:block-container>
																			</fo:table-cell>
																			<fo:table-cell border="0.01in solid black" padding="5" display-align="center">
																				<fo:block-container overflow="hidden">
																					<fo:block text-align="left">
																						<fo:inline font-size="0.13in">
																							<xsl:text>EUR</xsl:text>
																						</fo:inline>
																					</fo:block>
																				</fo:block-container>
																			</fo:table-cell>
																			<fo:table-cell border="0.01in solid black" padding="5" display-align="center">
																				<fo:block-container overflow="hidden">
																					<fo:block text-align="left">
																						<xsl:for-each select="insuredFrom">
																							<fo:inline>
																								<xsl:value-of select="format-number(number(substring(string(string(.)), 9, 2)), '00', 'format1')"/>
																								<xsl:text>.</xsl:text>
																								<xsl:value-of select="format-number(number(substring(string(string(.)), 6, 2)), '00', 'format1')"/>
																								<xsl:text>.</xsl:text>
																								<xsl:value-of select="format-number(number(substring(string(string(string(.))), 1, 4)), '0000', 'format1')"/>
																							</fo:inline>
																						</xsl:for-each>
																					</fo:block>
																				</fo:block-container>
																			</fo:table-cell>
																		</fo:table-row>
																	</xsl:variable>
																	<xsl:choose>
																		<xsl:when test="string($altova:tablerows)">
																			<xsl:copy-of select="$altova:tablerows"/>
																		</xsl:when>
																		<xsl:otherwise>
																			<fo:table-row>
																				<fo:table-cell>
																					<fo:block/>
																				</fo:table-cell>
																			</fo:table-row>
																		</xsl:otherwise>
																	</xsl:choose>
																</fo:table-body>
															</fo:table>
															<fo:block>
																<fo:leader leader-pattern="space"/>
															</fo:block>
														</fo:block>
													</fo:block-container>
												</fo:table-cell>
												<fo:table-cell padding-right="0.00in" padding="5" display-align="before">
													<fo:block-container overflow="hidden">
														<fo:block text-align="left">
															<fo:inline-container>
																<fo:block>
																	<xsl:text>&#x200B;</xsl:text>
																</fo:block>
															</fo:inline-container>
															<fo:table table-layout="fixed" width="100%" border-spacing="0">
																<fo:table-column column-width="proportional-column-width(1)"/>
																<fo:table-column column-width="proportional-column-width(1)"/>
																<fo:table-column column-width="proportional-column-width(1)"/>
																<xsl:variable name="altova:CurrContextGrid_15" select="."/>
																<fo:table-body start-indent="0pt">
																	<xsl:variable name="altova:tablerows">
																		<fo:table-row>
																			<fo:table-cell border="0.01in solid black" padding="5" display-align="center">
																				<fo:block-container overflow="hidden">
																					<fo:block text-align="left">
																						<fo:inline font-size="0.13in">
																							<xsl:text>variabilný symbol</xsl:text>
																						</fo:inline>
																					</fo:block>
																				</fo:block-container>
																			</fo:table-cell>
																			<fo:table-cell border="0.01in solid black" padding="5" display-align="center">
																				<fo:block-container overflow="hidden">
																					<fo:block text-align="left">
																						<fo:inline font-size="0.13in">
																							<xsl:text>konštantný symbol</xsl:text>
																						</fo:inline>
																					</fo:block>
																				</fo:block-container>
																			</fo:table-cell>
																			<fo:table-cell border="0.01in solid black" padding="5" display-align="center">
																				<fo:block-container overflow="hidden">
																					<fo:block text-align="left">
																						<fo:inline font-size="0.13in">
																							<xsl:text>špecifický symbol</xsl:text>
																						</fo:inline>
																					</fo:block>
																				</fo:block-container>
																			</fo:table-cell>
																		</fo:table-row>
																		<fo:table-row>
																			<fo:table-cell border="0.01in solid black" padding="5" display-align="center">
																				<fo:block-container overflow="hidden">
																					<fo:block text-align="left">
																						<xsl:for-each select="variableSymbol">
																							<xsl:variable name="value-of-template_16">
																								<xsl:apply-templates/>
																							</xsl:variable>
																							<xsl:choose>
																								<xsl:when test="contains(string($value-of-template_16),'&#x200B;')">
																									<fo:block>
																										<xsl:copy-of select="$value-of-template_16"/>
																									</fo:block>
																								</xsl:when>
																								<xsl:otherwise>
																									<fo:inline>
																										<xsl:copy-of select="$value-of-template_16"/>
																									</fo:inline>
																								</xsl:otherwise>
																							</xsl:choose>
																						</xsl:for-each>
																					</fo:block>
																				</fo:block-container>
																			</fo:table-cell>
																			<fo:table-cell border="0.01in solid black" padding="5" display-align="center">
																				<fo:block-container overflow="hidden">
																					<fo:block text-align="left">
																						<fo:inline font-size="0.13in">
																							<xsl:text>3558</xsl:text>
																						</fo:inline>
																					</fo:block>
																				</fo:block-container>
																			</fo:table-cell>
																			<fo:table-cell border="0.01in solid black" padding="5" display-align="center">
																				<fo:block-container overflow="hidden">
																					<fo:block text-align="left">
																						<fo:inline font-size="0.13in">
																							<xsl:text>0</xsl:text>
																						</fo:inline>
																					</fo:block>
																				</fo:block-container>
																			</fo:table-cell>
																		</fo:table-row>
																	</xsl:variable>
																	<xsl:choose>
																		<xsl:when test="string($altova:tablerows)">
																			<xsl:copy-of select="$altova:tablerows"/>
																		</xsl:when>
																		<xsl:otherwise>
																			<fo:table-row>
																				<fo:table-cell>
																					<fo:block/>
																				</fo:table-cell>
																			</fo:table-row>
																		</xsl:otherwise>
																	</xsl:choose>
																</fo:table-body>
															</fo:table>
														</fo:block>
													</fo:block-container>
												</fo:table-cell>
											</fo:table-row>
											<fo:table-row>
												<fo:table-cell number-columns-spanned="2" border="0.01in solid black" padding="5" display-align="center">
													<fo:block-container overflow="hidden">
														<fo:block text-align="left">
															<fo:inline font-size="0.13in">
																<xsl:text>Doplňujúci údaj banky</xsl:text>
															</fo:inline>
															<fo:block/>
															<fo:block>
																<fo:leader leader-pattern="space"/>
															</fo:block>
															<fo:block>
																<fo:leader leader-pattern="space"/>
															</fo:block>
														</fo:block>
													</fo:block-container>
												</fo:table-cell>
											</fo:table-row>
											<fo:table-row>
												<fo:table-cell number-columns-spanned="2" border="0.01in solid black" padding="5" display-align="center">
													<fo:block-container overflow="hidden">
														<fo:block text-align="left">
															<fo:inline font-size="0.13in">
																<xsl:text>Údaje pre vnútornú potrebu príkazcu</xsl:text>
															</fo:inline>
															<fo:block/>
															<fo:block>
																<fo:leader leader-pattern="space"/>
															</fo:block>
															<fo:block>
																<fo:leader leader-pattern="space"/>
															</fo:block>
														</fo:block>
													</fo:block-container>
												</fo:table-cell>
											</fo:table-row>
											<fo:table-row text-align="center">
												<fo:table-cell padding="5" display-align="center">
													<fo:block-container overflow="hidden">
														<fo:block text-align="center">
															<fo:block>
																<fo:leader leader-pattern="space"/>
															</fo:block>
															<fo:block>
																<fo:leader leader-pattern="space"/>
															</fo:block>
															<fo:inline-container>
																<fo:block>
																	<xsl:text>&#x200B;</xsl:text>
																</fo:block>
															</fo:inline-container>
															<fo:block font-size="0.13in" text-align="center" margin-right="100% - 100%" space-before="0" space-after="0" margin="0pt">
																<fo:inline font-size="0.13in">
																	<xsl:text>-----------------------------------------------</xsl:text>
																</fo:inline>
																<fo:block/>
																<fo:inline font-size="0.13in">
																	<xsl:text>miesto a dátum vystavenia</xsl:text>
																</fo:inline>
															</fo:block>
														</fo:block>
													</fo:block-container>
												</fo:table-cell>
												<fo:table-cell padding="5" display-align="center">
													<fo:block-container overflow="hidden">
														<fo:block text-align="center">
															<fo:block>
																<fo:leader leader-pattern="space"/>
															</fo:block>
															<fo:block>
																<fo:leader leader-pattern="space"/>
															</fo:block>
															<fo:inline font-size="0.13in">
																<xsl:text>-----------------------------------------------</xsl:text>
															</fo:inline>
															<fo:block/>
															<fo:inline font-size="0.13in">
																<xsl:text>pečiatka a podpis príkazcu </xsl:text>
															</fo:inline>
														</fo:block>
													</fo:block-container>
												</fo:table-cell>
											</fo:table-row>
										</xsl:variable>
										<xsl:choose>
											<xsl:when test="string($altova:tablerows)">
												<xsl:copy-of select="$altova:tablerows"/>
											</xsl:when>
											<xsl:otherwise>
												<fo:table-row>
													<fo:table-cell>
														<fo:block/>
													</fo:table-cell>
												</fo:table-row>
											</xsl:otherwise>
										</xsl:choose>
									</fo:table-body>
								</fo:table>
							</xsl:for-each>
						</xsl:for-each>
						<fo:block/>
					</fo:block>
					<fo:block id="SV_RefID_PageTotal"/>
				</fo:flow>
			</fo:page-sequence>
		</fo:root>
	</xsl:template>
	<xsl:template name="altova:double-backslash">
		<xsl:param name="text"/>
		<xsl:param name="text-length"/>
		<xsl:variable name="text-after-bs" select="substring-after($text, '\')"/>
		<xsl:variable name="text-after-bs-length" select="string-length($text-after-bs)"/>
		<xsl:choose>
			<xsl:when test="$text-after-bs-length = 0">
				<xsl:choose>
					<xsl:when test="substring($text, $text-length) = '\'">
						<xsl:value-of select="concat(substring($text,1,$text-length - 1), '\\')"/>
					</xsl:when>
					<xsl:otherwise>
						<xsl:value-of select="$text"/>
					</xsl:otherwise>
				</xsl:choose>
			</xsl:when>
			<xsl:otherwise>
				<xsl:value-of select="concat(substring($text,1,$text-length - $text-after-bs-length - 1), '\\')"/>
				<xsl:call-template name="altova:double-backslash">
					<xsl:with-param name="text" select="$text-after-bs"/>
					<xsl:with-param name="text-length" select="$text-after-bs-length"/>
				</xsl:call-template>
			</xsl:otherwise>
		</xsl:choose>
	</xsl:template>
	<xsl:template name="altova:MakeValueAbsoluteIfPixels">
		<xsl:param name="sValue"/>
		<xsl:variable name="sBeforePx" select="substring-before($sValue, 'px')"/>
		<xsl:choose>
			<xsl:when test="$sBeforePx">
				<xsl:variable name="nLengthOfInteger">
					<xsl:call-template name="altova:GetCharCountOfIntegerAtEndOfString">
						<xsl:with-param name="sText" select="$sBeforePx"/>
					</xsl:call-template>
				</xsl:variable>
				<xsl:variable name="nPosOfInteger" select="string-length($sBeforePx) - $nLengthOfInteger + 1"/>
				<xsl:variable name="nValuePx" select="substring($sBeforePx, $nPosOfInteger)"/>
				<xsl:variable name="nValueIn" select="number($nValuePx) div number($altova:nPxPerIn)"/>
				<xsl:variable name="nLengthBeforeInteger" select="string-length($sBeforePx) - $nLengthOfInteger"/>
				<xsl:variable name="sRest">
					<xsl:call-template name="altova:MakeValueAbsoluteIfPixels">
						<xsl:with-param name="sValue" select="substring-after($sValue, 'px')"/>
					</xsl:call-template>
				</xsl:variable>
				<xsl:value-of select="concat(substring($sBeforePx, 1, $nLengthBeforeInteger), string($nValueIn), 'in', $sRest)"/>
			</xsl:when>
			<xsl:otherwise>
				<xsl:value-of select="$sValue"/>
			</xsl:otherwise>
		</xsl:choose>
	</xsl:template>
	<xsl:template name="altova:GetCharCountOfIntegerAtEndOfString">
		<xsl:param name="sText"/>
		<xsl:variable name="sLen" select="string-length($sText)"/>
		<xsl:variable name="cLast" select="substring($sText, $sLen)"/>
		<xsl:choose>
			<xsl:when test="number($cLast) &gt;= 0 and number($cLast) &lt;= 9">
				<xsl:variable name="nResultOfRest">
					<xsl:call-template name="altova:GetCharCountOfIntegerAtEndOfString">
						<xsl:with-param name="sText" select="substring($sText, 1, $sLen - 1)"/>
					</xsl:call-template>
				</xsl:variable>
				<xsl:value-of select="$nResultOfRest + 1"/>
			</xsl:when>
			<xsl:otherwise>
				<xsl:text>0</xsl:text>
			</xsl:otherwise>
		</xsl:choose>
	</xsl:template>
</xsl:stylesheet>
