<?xml version="1.0" encoding="UTF-8"?>
<!--Designed and generated by Altova StyleVision Enterprise Edition 2013 rel. 2 sp2 (x64) - see http://www.altova.com/stylevision for more information.-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:altova="http://www.altova.com" xmlns:altovaext="http://www.altova.com/xslt-extensions" xmlns:clitype="clitype" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:iso4217="http://www.xbrl.org/2003/iso4217" xmlns:ix="http://www.xbrl.org/2008/inlineXBRL" xmlns:java="java" xmlns:link="http://www.xbrl.org/2003/linkbase" xmlns:sps="http://www.altova.com/StyleVision/user-xpath-functions" xmlns:xbrldi="http://xbrl.org/2006/xbrldi" xmlns:xbrli="http://www.xbrl.org/2003/instance" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:fo="http://www.w3.org/1999/XSL/Format" xmlns:svg="http://www.w3.org/2000/svg" exclude-result-prefixes="altova altovaext clitype fn iso4217 ix java link sps xbrldi xbrli xlink xs xsi">
	<xsl:output version="1.0" method="xml" encoding="UTF-8" indent="no"/>
	<xsl:param name="SV_OutputFormat" select="'PDF'"/>
	<xsl:variable name="XML" select="/"/>
	<xsl:decimal-format name="format1" grouping-separator=" " decimal-separator=","/>
	<xsl:variable name="fo:layout-master-set">
		<fo:layout-master-set>
			<fo:simple-page-master master-name="page-master-0-even" margin-left="0.3in" margin-right="0.3in" page-height="11.69in" page-width="8.26in" margin-top="0" margin-bottom="0">
				<fo:region-body margin-top="0.30in" margin-bottom="0.30in" column-count="1" column-gap="0"/>
			</fo:simple-page-master>
			<fo:simple-page-master master-name="page-master-0-odd" margin-left="0.3in" margin-right="0.3in" page-height="11.69in" page-width="8.26in" margin-top="0" margin-bottom="0">
				<fo:region-body margin-top="0.30in" margin-bottom="0.30in" column-count="1" column-gap="0"/>
			</fo:simple-page-master>
			<fo:page-sequence-master master-name="page-master-0">
				<fo:repeatable-page-master-alternatives>
					<fo:conditional-page-master-reference master-reference="page-master-0-even" odd-or-even="even"/>
					<fo:conditional-page-master-reference master-reference="page-master-0-odd" odd-or-even="odd"/>
				</fo:repeatable-page-master-alternatives>
			</fo:page-sequence-master>
		</fo:layout-master-set>
	</xsl:variable>
	<xsl:variable name="altova:nPxPerIn" select="96"/>
	<xsl:template match="/">
		<fo:root>
			<xsl:copy-of select="$fo:layout-master-set"/>
			<fo:declarations>
				<x:xmpmeta xmlns:x="adobe:ns:meta/">
					<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
						<rdf:Description rdf:about="" xmlns:xmp="http://ns.adobe.com/xap/1.0/">
							<xmp:CreatorTool>Altova StyleVision Enterprise Edition 2013 rel. 2 sp2 (x64) (http://www.altova.com)</xmp:CreatorTool>
						</rdf:Description>
					</rdf:RDF>
				</x:xmpmeta>
			</fo:declarations>
			<fo:page-sequence force-page-count="no-force" master-reference="page-master-0" initial-page-number="auto" format="1">
				<fo:flow flow-name="xsl-region-body">
					<fo:block font-family="Arial" font-size="8px">
						<xsl:for-each select="$XML">
							<fo:inline-container>
								<fo:block>
									<xsl:text>&#x200B;</xsl:text>
								</fo:block>
							</fo:inline-container>
							<xsl:if test="agreement">
								<fo:table font-family="Arial" font-size="0.08in" margin-left="0.25in" width="6.96in" table-layout="fixed" border-spacing="2pt">
									<fo:table-column column-width="proportional-column-width(1)"/>
									<xsl:variable name="altova:CurrContextGrid_1" select="."/>
									<fo:table-body start-indent="0pt">
										<xsl:variable name="altova:tablerows">
											<xsl:for-each select="agreement">
												<xsl:for-each select="insuredPersons">
													<xsl:for-each select="person">
														<fo:table-row keep-together.within-page="always" keep-together.within-column="always">
															<fo:table-cell padding="2pt" display-align="center">
																<fo:block-container overflow="hidden">
																	<fo:block text-align="left">
																		<fo:inline-container>
																			<fo:block>
																				<xsl:text>&#x200B;</xsl:text>
																			</fo:block>
																		</fo:inline-container>
																		<fo:table text-align="center" width="6.96in" table-layout="fixed" border-spacing="0">
																			<fo:table-column column-width="0.100in"/>
																			<fo:table-column column-width="1.640in"/>
																			<fo:table-column column-width="1.740in"/>
																			<fo:table-column column-width="1.640in"/>
																			<fo:table-column column-width="1.740in"/>
																			<fo:table-column column-width="0.100in"/>
																			<xsl:variable name="altova:CurrContextGrid_2" select="."/>
																			<fo:table-body start-indent="0pt">
																				<xsl:variable name="altova:tablerows">
																					<fo:table-row>
																						<fo:table-cell padding="2pt" display-align="center">
																							<fo:block-container overflow="hidden">
																								<fo:block text-align="left"/>
																							</fo:block-container>
																						</fo:table-cell>
																						<fo:table-cell padding="2pt" display-align="center">
																							<fo:block-container overflow="hidden">
																								<fo:block text-align="left"/>
																							</fo:block-container>
																						</fo:table-cell>
																						<fo:table-cell number-columns-spanned="2" padding="2pt" display-align="center">
																							<fo:block-container overflow="hidden">
																								<fo:block text-align="left"/>
																							</fo:block-container>
																						</fo:table-cell>
																						<fo:table-cell padding="2pt" display-align="center">
																							<fo:block-container overflow="hidden">
																								<fo:block text-align="left"/>
																							</fo:block-container>
																						</fo:table-cell>
																						<fo:table-cell padding="2pt" display-align="center">
																							<fo:block-container overflow="hidden">
																								<fo:block text-align="left"/>
																							</fo:block-container>
																						</fo:table-cell>
																					</fo:table-row>
																					<fo:table-row padding="0">
																						<fo:table-cell number-columns-spanned="2" padding-left="0.06in" padding="2pt" display-align="after">
																							<fo:block-container overflow="hidden">
																								<fo:block text-align="left">
																									<fo:external-graphic content-width="60%" scaling="non-uniform">
																										<xsl:attribute name="src">
																											<xsl:text>url(</xsl:text>
																											<xsl:call-template name="altova:double-backslash">
																												<xsl:with-param name="text">
																													<xsl:value-of select="string(&apos;cut.jpg&apos;)"/>
																												</xsl:with-param>
																												<xsl:with-param name="text-length">
																													<xsl:value-of select="string-length(string(&apos;cut.jpg&apos;))"/>
																												</xsl:with-param>
																											</xsl:call-template>
																											<xsl:text>)</xsl:text>
																										</xsl:attribute>
																									</fo:external-graphic>
																									<fo:inline>
																										<xsl:text>&#x200B;</xsl:text>
																									</fo:inline>
																								</fo:block>
																							</fo:block-container>
																						</fo:table-cell>
																						<fo:table-cell number-columns-spanned="2" padding-left="1.65in" padding="2pt" display-align="center">
																							<fo:block-container overflow="hidden">
																								<fo:block text-align="left">
																									<fo:external-graphic content-width="0.20in" scaling="non-uniform">
																										<xsl:attribute name="src">
																											<xsl:text>url(</xsl:text>
																											<xsl:call-template name="altova:double-backslash">
																												<xsl:with-param name="text">
																													<xsl:value-of select="string(&apos;card_top.jpg&apos;)"/>
																												</xsl:with-param>
																												<xsl:with-param name="text-length">
																													<xsl:value-of select="string-length(string(&apos;card_top.jpg&apos;))"/>
																												</xsl:with-param>
																											</xsl:call-template>
																											<xsl:text>)</xsl:text>
																										</xsl:attribute>
																									</fo:external-graphic>
																									<fo:inline>
																										<xsl:text>&#x200B;</xsl:text>
																									</fo:inline>
																								</fo:block>
																							</fo:block-container>
																						</fo:table-cell>
																						<fo:table-cell padding="2pt" display-align="center">
																							<fo:block-container overflow="hidden">
																								<fo:block text-align="left"/>
																							</fo:block-container>
																						</fo:table-cell>
																						<fo:table-cell padding="2pt" display-align="center">
																							<fo:block-container overflow="hidden">
																								<fo:block text-align="left"/>
																							</fo:block-container>
																						</fo:table-cell>
																					</fo:table-row>
																					<fo:table-row padding="0">
																						<fo:table-cell border-right="0.01in solid black" padding="0" display-align="center">
																							<fo:block-container overflow="hidden">
																								<fo:block text-align="left"/>
																							</fo:block-container>
																						</fo:table-cell>
																						<fo:table-cell padding="2pt" display-align="center">
																							<fo:block-container overflow="hidden">
																								<fo:block text-align="left"/>
																							</fo:block-container>
																						</fo:table-cell>
																						<fo:table-cell border-right="0.01in solid black" padding="2pt" display-align="center">
																							<fo:block-container overflow="hidden">
																								<fo:block text-align="left"/>
																							</fo:block-container>
																						</fo:table-cell>
																						<fo:table-cell padding="2pt" display-align="center">
																							<fo:block-container overflow="hidden">
																								<fo:block text-align="left"/>
																							</fo:block-container>
																						</fo:table-cell>
																						<fo:table-cell border-right="0.01in solid black" padding="2pt" display-align="center">
																							<fo:block-container overflow="hidden">
																								<fo:block text-align="left"/>
																							</fo:block-container>
																						</fo:table-cell>
																						<fo:table-cell padding="2pt" display-align="center">
																							<fo:block-container overflow="hidden">
																								<fo:block text-align="left"/>
																							</fo:block-container>
																						</fo:table-cell>
																					</fo:table-row>
																					<fo:table-row border-top="0.01in solid black" height="0.16in">
																						<fo:table-cell padding="2pt" display-align="center">
																							<fo:block-container overflow="hidden">
																								<fo:block text-align="left"/>
																							</fo:block-container>
																						</fo:table-cell>
																						<fo:table-cell border-left="0.01in solid black" padding="0" padding-left="0.08in" display-align="center">
																							<fo:block-container overflow="hidden">
																								<fo:block text-align="left">
																									<fo:external-graphic content-width="0.55in" scaling="non-uniform">
																										<xsl:attribute name="src">
																											<xsl:text>url(</xsl:text>
																											<xsl:call-template name="altova:double-backslash">
																												<xsl:with-param name="text">
																													<xsl:value-of select="string(&apos;logo.jpg&apos;)"/>
																												</xsl:with-param>
																												<xsl:with-param name="text-length">
																													<xsl:value-of select="string-length(string(&apos;logo.jpg&apos;))"/>
																												</xsl:with-param>
																											</xsl:call-template>
																											<xsl:text>)</xsl:text>
																										</xsl:attribute>
																									</fo:external-graphic>
																									<fo:inline>
																										<xsl:text>&#x200B;</xsl:text>
																									</fo:inline>
																								</fo:block>
																							</fo:block-container>
																						</fo:table-cell>
																						<fo:table-cell border-right="0.01in solid black" padding="0" padding-left="0.63in" display-align="center">
																							<fo:block-container overflow="hidden">
																								<fo:block text-align="left">
																									<fo:external-graphic content-width="0.24in" scaling="non-uniform">
																										<xsl:attribute name="src">
																											<xsl:text>url(</xsl:text>
																											<xsl:call-template name="altova:double-backslash">
																												<xsl:with-param name="text">
																													<xsl:value-of select="string(&apos;eurocross.jpg&apos;)"/>
																												</xsl:with-param>
																												<xsl:with-param name="text-length">
																													<xsl:value-of select="string-length(string(&apos;eurocross.jpg&apos;))"/>
																												</xsl:with-param>
																											</xsl:call-template>
																											<xsl:text>)</xsl:text>
																										</xsl:attribute>
																									</fo:external-graphic>
																									<fo:inline>
																										<xsl:text>&#x200B;</xsl:text>
																									</fo:inline>
																								</fo:block>
																							</fo:block-container>
																						</fo:table-cell>
																						<fo:table-cell padding="0" padding-left="0.16in" display-align="center">
																							<fo:block-container overflow="hidden">
																								<fo:block text-align="left">
																									<fo:external-graphic content-width="0.55in" scaling="non-uniform">
																										<xsl:attribute name="src">
																											<xsl:text>url(</xsl:text>
																											<xsl:call-template name="altova:double-backslash">
																												<xsl:with-param name="text">
																													<xsl:value-of select="string(&apos;logo.jpg&apos;)"/>
																												</xsl:with-param>
																												<xsl:with-param name="text-length">
																													<xsl:value-of select="string-length(string(&apos;logo.jpg&apos;))"/>
																												</xsl:with-param>
																											</xsl:call-template>
																											<xsl:text>)</xsl:text>
																										</xsl:attribute>
																									</fo:external-graphic>
																									<fo:inline>
																										<xsl:text>&#x200B;</xsl:text>
																									</fo:inline>
																								</fo:block>
																							</fo:block-container>
																						</fo:table-cell>
																						<fo:table-cell border-right="0.01in solid black" padding="0" padding-right="0.16in" display-align="center">
																							<fo:block-container overflow="hidden">
																								<fo:block text-align="right">
																									<fo:external-graphic content-width="0.24in" scaling="non-uniform">
																										<xsl:attribute name="src">
																											<xsl:text>url(</xsl:text>
																											<xsl:call-template name="altova:double-backslash">
																												<xsl:with-param name="text">
																													<xsl:value-of select="string(&apos;eurocross.jpg&apos;)"/>
																												</xsl:with-param>
																												<xsl:with-param name="text-length">
																													<xsl:value-of select="string-length(string(&apos;eurocross.jpg&apos;))"/>
																												</xsl:with-param>
																											</xsl:call-template>
																											<xsl:text>)</xsl:text>
																										</xsl:attribute>
																									</fo:external-graphic>
																									<fo:inline>
																										<xsl:text>&#x200B;</xsl:text>
																									</fo:inline>
																								</fo:block>
																							</fo:block-container>
																						</fo:table-cell>
																						<fo:table-cell padding="2pt" display-align="center">
																							<fo:block-container overflow="hidden">
																								<fo:block text-align="left"/>
																							</fo:block-container>
																						</fo:table-cell>
																					</fo:table-row>
																					<fo:table-row>
																						<fo:table-cell padding="2pt" display-align="center">
																							<fo:block-container overflow="hidden">
																								<fo:block text-align="left"/>
																							</fo:block-container>
																						</fo:table-cell>
																						<fo:table-cell number-rows-spanned="2" border-left="0.01in solid black" padding-left="0.05in" padding="2pt" display-align="before">
																							<fo:block-container overflow="hidden">
																								<fo:block text-align="left">
																									<fo:inline>
																										<xsl:text>Union poisťovňa, a.s.</xsl:text>
																									</fo:inline>
																									<fo:block/>
																									<fo:inline>
																										<xsl:text>Bajkalská 29/A</xsl:text>
																									</fo:inline>
																									<fo:block/>
																									<fo:inline>
																										<xsl:text>813 60 Bratislava</xsl:text>
																									</fo:inline>
																									<fo:block/>
																									<fo:inline>
																										<xsl:text>Slovenská republika</xsl:text>
																									</fo:inline>
																								</fo:block>
																							</fo:block-container>
																						</fo:table-cell>
																						<fo:table-cell number-rows-spanned="2" border-right="0.01in solid black" padding-left="0.05in" padding="2pt" display-align="before">
																							<fo:block-container overflow="hidden">
																								<fo:block text-align="left">
																									<fo:inline>
																										<xsl:text>EuroCross Assistance Czech Republic</xsl:text>
																									</fo:inline>
																									<fo:block/>
																									<fo:inline>
																										<xsl:text>Lazarská 13/8</xsl:text>
																									</fo:inline>
																									<fo:block/>
																									<fo:inline>
																										<xsl:text>120 00 Praha 2</xsl:text>
																									</fo:inline>
																									<fo:block/>
																									<fo:inline>
																										<xsl:text>Česká republika</xsl:text>
																									</fo:inline>
																								</fo:block>
																							</fo:block-container>
																						</fo:table-cell>
																						<fo:table-cell number-columns-spanned="2" background-color="#D7002C" border-right="0.01in solid black" font-size="0.14in" padding-top="0.05in" padding="2pt" display-align="center">
																							<fo:block-container overflow="hidden">
																								<fo:block text-align="center">
																									<fo:inline color="white" font-size="0.14in" font-weight="bold">
																										<xsl:text>CESTOVNÉ POISTENIE</xsl:text>
																									</fo:inline>
																									<fo:block/>
																								</fo:block>
																							</fo:block-container>
																						</fo:table-cell>
																						<fo:table-cell padding="2pt" display-align="center">
																							<fo:block-container overflow="hidden">
																								<fo:block text-align="left"/>
																							</fo:block-container>
																						</fo:table-cell>
																					</fo:table-row>
																					<fo:table-row>
																						<fo:table-cell padding="2pt" display-align="center">
																							<fo:block-container overflow="hidden">
																								<fo:block text-align="left"/>
																							</fo:block-container>
																						</fo:table-cell>
																						<fo:table-cell number-columns-spanned="2" background-color="#D7002C" border-right="0.01in solid black" font-size="0.14in" padding="2pt" display-align="center">
																							<fo:block-container overflow="hidden">
																								<fo:block text-align="center">
																									<fo:inline color="white">
																										<xsl:text>Travel Insurance / Reiseversicherung</xsl:text>
																									</fo:inline>
																								</fo:block>
																							</fo:block-container>
																						</fo:table-cell>
																						<fo:table-cell padding="2pt" display-align="center">
																							<fo:block-container overflow="hidden">
																								<fo:block text-align="left"/>
																							</fo:block-container>
																						</fo:table-cell>
																					</fo:table-row>
																					<fo:table-row>
																						<fo:table-cell padding="2pt" display-align="center">
																							<fo:block-container overflow="hidden">
																								<fo:block text-align="left"/>
																							</fo:block-container>
																						</fo:table-cell>
																						<fo:table-cell border-left="0.01in solid black" padding="0" padding-left="0.05in" display-align="before">
																							<fo:block-container overflow="hidden">
																								<fo:block text-align="left">
																									<fo:inline>
																										<xsl:text>tel: + 421 2 20 811 811</xsl:text>
																									</fo:inline>
																								</fo:block>
																							</fo:block-container>
																						</fo:table-cell>
																						<fo:table-cell border-right="0.01in solid black" padding="0" padding-left="0.05in" display-align="before">
																							<fo:block-container overflow="hidden">
																								<fo:block text-align="left">
																									<fo:inline>
																										<xsl:text>tel: + 420 2 9633 9644</xsl:text>
																									</fo:inline>
																								</fo:block>
																							</fo:block-container>
																						</fo:table-cell>
																						<fo:table-cell number-columns-spanned="2" border-right="0.01in solid black" font-size="0.11in" padding="0" display-align="center">
																							<fo:block-container overflow="hidden">
																								<fo:block text-align="center">
																									<fo:inline font-weight="bold">
																										<xsl:text>V prípade potreby volajte asistenčnú spoločnosť</xsl:text>
																									</fo:inline>
																								</fo:block>
																							</fo:block-container>
																						</fo:table-cell>
																						<fo:table-cell padding="2pt" display-align="center">
																							<fo:block-container overflow="hidden">
																								<fo:block text-align="left"/>
																							</fo:block-container>
																						</fo:table-cell>
																					</fo:table-row>
																					<fo:table-row>
																						<fo:table-cell padding="2pt" display-align="center">
																							<fo:block-container overflow="hidden">
																								<fo:block text-align="left"/>
																							</fo:block-container>
																						</fo:table-cell>
																						<fo:table-cell number-columns-spanned="2" number-rows-spanned="3" border-left="0.01in solid black" border-right="0.01in solid black" padding="0" padding-left="0.05in" padding-right="0.05in" display-align="before">
																							<fo:block-container overflow="hidden">
																								<fo:block text-align="justify">
																									<fo:inline>
																										<xsl:text>V prípade potreby lekárskej pomoci sa preukážte lekárovi touto poistnou kartou alebo poistnou zmluvou. V prípade vážnejšieho zdravotného stavu, hospitalizácie alebo ak potrebujete pomoc, telefonicky sa skontaktujte s pracovníkmi asistenčnej spoločnosti EuroCross Assistance, ktorá ma nepretržitú prevádzku. Hovoriť môžete po slovensky.</xsl:text>
																									</fo:inline>
																								</fo:block>
																							</fo:block-container>
																						</fo:table-cell>
																						<fo:table-cell background-color="#D7002C" font-size="0.14in" padding-bottom="0.01in" padding-top="0.02in" padding="2pt" display-align="center">
																							<fo:block-container overflow="hidden">
																								<fo:block text-align="center">
																									<fo:inline color="white" font-weight="bold">
																										<xsl:text>+ 420 2 9633 9644</xsl:text>
																									</fo:inline>
																								</fo:block>
																							</fo:block-container>
																						</fo:table-cell>
																						<fo:table-cell background-color="#D7002C" border-right="0.01in solid black" font-size="0.14in" padding-bottom="0.01in" padding-top="0.02in" padding="2pt" display-align="center">
																							<fo:block-container overflow="hidden">
																								<fo:block text-align="center">
																									<fo:inline color="white" font-weight="bold">
																										<xsl:text>+ 31 71 36 41 212</xsl:text>
																									</fo:inline>
																								</fo:block>
																							</fo:block-container>
																						</fo:table-cell>
																						<fo:table-cell padding="2pt" display-align="center">
																							<fo:block-container overflow="hidden">
																								<fo:block text-align="left"/>
																							</fo:block-container>
																						</fo:table-cell>
																					</fo:table-row>
																					<fo:table-row>
																						<fo:table-cell padding="2pt" display-align="center">
																							<fo:block-container overflow="hidden">
																								<fo:block text-align="left"/>
																							</fo:block-container>
																						</fo:table-cell>
																						<fo:table-cell font-size="0.11in" padding="0" padding-left="0.10in" padding-top="0.01in" display-align="center">
																							<fo:block-container overflow="hidden">
																								<fo:block text-align="left">
																									<fo:inline>
																										<xsl:text>Poistná zmluva č.</xsl:text>
																									</fo:inline>
																								</fo:block>
																							</fo:block-container>
																						</fo:table-cell>
																						<fo:table-cell border-right="0.01in solid black" font-size="0.11in" padding="0" padding-left="0.10in" display-align="center">
																							<fo:block-container overflow="hidden">
																								<fo:block text-align="left">
																									<fo:inline>
																										<xsl:text>Poistné obdobie</xsl:text>
																									</fo:inline>
																								</fo:block>
																							</fo:block-container>
																						</fo:table-cell>
																						<fo:table-cell padding="2pt" display-align="center">
																							<fo:block-container overflow="hidden">
																								<fo:block text-align="left"/>
																							</fo:block-container>
																						</fo:table-cell>
																					</fo:table-row>
																					<fo:table-row>
																						<fo:table-cell padding="2pt" display-align="center">
																							<fo:block-container overflow="hidden">
																								<fo:block text-align="left"/>
																							</fo:block-container>
																						</fo:table-cell>
																						<fo:table-cell number-rows-spanned="3" background-color="#D9D9D9" font-size="0.14in" font-weight="bold" padding-bottom="0.05in" padding-left="0.10in" padding-right="0.10in" padding-top="0.05in" padding="2pt" display-align="center">
																							<fo:block-container overflow="hidden">
																								<fo:block text-align="left">
																									<xsl:for-each select="$XML">
																										<xsl:for-each select="agreement">
																											<xsl:for-each select="variableSymbol">
																												<xsl:variable name="value-of-template_3">
																													<xsl:apply-templates/>
																												</xsl:variable>
																												<xsl:choose>
																													<xsl:when test="contains(string($value-of-template_3),'&#x200B;')">
																														<fo:block>
																															<xsl:copy-of select="$value-of-template_3"/>
																														</fo:block>
																													</xsl:when>
																													<xsl:otherwise>
																														<fo:inline>
																															<xsl:copy-of select="$value-of-template_3"/>
																														</fo:inline>
																													</xsl:otherwise>
																												</xsl:choose>
																											</xsl:for-each>
																										</xsl:for-each>
																									</xsl:for-each>
																								</fo:block>
																							</fo:block-container>
																						</fo:table-cell>
																						<fo:table-cell number-rows-spanned="3" background-color="#D9D9D9" border-right="0.01in solid black" font-size="0.14in" font-weight="bold" padding="0.05in 0.10in" display-align="center">
																							<fo:block-container overflow="hidden">
																								<fo:block text-align="left">
																									<xsl:for-each select="$XML">
																										<xsl:for-each select="agreement">
																											<xsl:for-each select="insuredFrom">
																												<xsl:for-each select="@sk">
																													<fo:inline>
																														<xsl:value-of select="format-number(number(substring(string(string(.)), 9, 2)), '00', 'format1')"/>
																														<xsl:text>.</xsl:text>
																														<xsl:value-of select="format-number(number(substring(string(string(.)), 6, 2)), '00', 'format1')"/>
																														<xsl:text>.</xsl:text>
																														<xsl:value-of select="format-number(number(substring(string(string(string(.))), 1, 4)), '0000', 'format1')"/>
																													</fo:inline>
																												</xsl:for-each>
																											</xsl:for-each>
																										</xsl:for-each>
																									</xsl:for-each>
																									<fo:inline>
																										<xsl:text> - </xsl:text>
																									</fo:inline>
																									<xsl:for-each select="$XML">
																										<xsl:for-each select="agreement">
																											<xsl:for-each select="insuredTo">
																												<xsl:for-each select="@sk">
																													<fo:inline>
																														<xsl:value-of select="format-number(number(substring(string(string(.)), 9, 2)), '00', 'format1')"/>
																														<xsl:text>.</xsl:text>
																														<xsl:value-of select="format-number(number(substring(string(string(.)), 6, 2)), '00', 'format1')"/>
																														<xsl:text>.</xsl:text>
																														<xsl:value-of select="format-number(number(substring(string(string(string(.))), 1, 4)), '0000', 'format1')"/>
																													</fo:inline>
																												</xsl:for-each>
																											</xsl:for-each>
																										</xsl:for-each>
																									</xsl:for-each>
																								</fo:block>
																							</fo:block-container>
																						</fo:table-cell>
																						<fo:table-cell padding="2pt" display-align="center">
																							<fo:block-container overflow="hidden">
																								<fo:block text-align="left"/>
																							</fo:block-container>
																						</fo:table-cell>
																					</fo:table-row>
																					<fo:table-row>
																						<fo:table-cell padding="2pt" display-align="center">
																							<fo:block-container overflow="hidden">
																								<fo:block text-align="left"/>
																							</fo:block-container>
																						</fo:table-cell>
																						<fo:table-cell number-columns-spanned="2" border-left="0.01in solid black" border-right="0.01in solid black" padding="0" display-align="center">
																							<fo:block-container overflow="hidden">
																								<fo:block text-align="center">
																									<fo:inline>
																										<xsl:text>Z celého sveta platné tel. čísla asistenčnej spoločnosti EuroCross Assistance</xsl:text>
																									</fo:inline>
																								</fo:block>
																							</fo:block-container>
																						</fo:table-cell>
																						<fo:table-cell padding="2pt" display-align="center">
																							<fo:block-container overflow="hidden">
																								<fo:block text-align="left"/>
																							</fo:block-container>
																						</fo:table-cell>
																					</fo:table-row>
																					<fo:table-row>
																						<fo:table-cell padding="2pt" display-align="center">
																							<fo:block-container overflow="hidden">
																								<fo:block text-align="left"/>
																							</fo:block-container>
																						</fo:table-cell>
																						<fo:table-cell number-rows-spanned="2" background-color="#D7002C" border-left="0.01in solid black" font-size="0.14in" padding="2pt" display-align="center">
																							<fo:block-container overflow="hidden">
																								<fo:block text-align="center">
																									<fo:inline color="white" font-weight="bold">
																										<xsl:text>+ 420 2 9633 9644</xsl:text>
																									</fo:inline>
																								</fo:block>
																							</fo:block-container>
																						</fo:table-cell>
																						<fo:table-cell number-rows-spanned="2" background-color="#D7002C" border-right="0.01in solid black" font-size="0.14in" padding="2pt" display-align="center">
																							<fo:block-container overflow="hidden">
																								<fo:block text-align="center">
																									<fo:inline color="white" font-weight="bold">
																										<xsl:text>+ 31 71 36 41 212</xsl:text>
																									</fo:inline>
																								</fo:block>
																							</fo:block-container>
																						</fo:table-cell>
																						<fo:table-cell padding="2pt" display-align="center">
																							<fo:block-container overflow="hidden">
																								<fo:block text-align="left"/>
																							</fo:block-container>
																						</fo:table-cell>
																					</fo:table-row>
																					<fo:table-row>
																						<fo:table-cell padding="2pt" display-align="center">
																							<fo:block-container overflow="hidden">
																								<fo:block text-align="left"/>
																							</fo:block-container>
																						</fo:table-cell>
																						<fo:table-cell number-columns-spanned="2" border-right="0.01in solid black" font-size="0.11in" font-weight="normal" padding="0" padding-left="0.10in" padding-right="0.10in" padding-top="0.01in" display-align="center">
																							<fo:block-container overflow="hidden">
																								<fo:block text-align="left">
																									<fo:inline>
																										<xsl:text>Meno a priezvisko poisteného</xsl:text>
																									</fo:inline>
																								</fo:block>
																							</fo:block-container>
																						</fo:table-cell>
																						<fo:table-cell padding="2pt" display-align="center">
																							<fo:block-container overflow="hidden">
																								<fo:block text-align="left"/>
																							</fo:block-container>
																						</fo:table-cell>
																					</fo:table-row>
																					<fo:table-row>
																						<fo:table-cell padding="2pt" display-align="center">
																							<fo:block-container overflow="hidden">
																								<fo:block text-align="left"/>
																							</fo:block-container>
																						</fo:table-cell>
																						<fo:table-cell number-columns-spanned="2" border-bottom="0.01in solid black" border-left="0.01in solid black" border-right="0.01in solid black" padding-left="0.05in" padding="2pt" display-align="center">
																							<fo:block-container overflow="hidden">
																								<fo:block text-align="center">
																									<fo:inline>
																										<xsl:text>Z krajín Anglicko, Francúzsko, Nemecko, Rakúsko, Taliansko, Španielsko, Švajčiarsko, Kanada a USA je možné využiť aj bezplatné telefónne číslo asistenčnej spoločnosti EuroCross Assistance:</xsl:text>
																									</fo:inline>
																									<fo:block/>
																									<fo:inline font-weight="bold">
																										<xsl:text>+ 800 41 212 212</xsl:text>
																									</fo:inline>
																									<fo:inline>
																										<xsl:text>. Pozor! Toto číslo nie je možné použiť ako bezplatné z mobilného telefónu.</xsl:text>
																									</fo:inline>
																								</fo:block>
																							</fo:block-container>
																						</fo:table-cell>
																						<fo:table-cell number-columns-spanned="2" background-color="#D9D9D9" border-bottom="0.01in solid black" border-right="0.01in solid black" font-size="0.14in" font-weight="bold" padding-left="0.10in" padding="2pt" display-align="center">
																							<fo:block-container overflow="hidden">
																								<fo:block text-align="left">
																									<xsl:for-each select="name">
																										<xsl:variable name="value-of-template_6">
																											<xsl:apply-templates/>
																										</xsl:variable>
																										<xsl:choose>
																											<xsl:when test="contains(string($value-of-template_6),'&#x200B;')">
																												<fo:block>
																													<xsl:copy-of select="$value-of-template_6"/>
																												</fo:block>
																											</xsl:when>
																											<xsl:otherwise>
																												<fo:inline>
																													<xsl:copy-of select="$value-of-template_6"/>
																												</fo:inline>
																											</xsl:otherwise>
																										</xsl:choose>
																									</xsl:for-each>
																									<fo:inline>
																										<xsl:text>&#160;</xsl:text>
																									</fo:inline>
																									<xsl:for-each select="surname">
																										<xsl:variable name="value-of-template_7">
																											<xsl:apply-templates/>
																										</xsl:variable>
																										<xsl:choose>
																											<xsl:when test="contains(string($value-of-template_7),'&#x200B;')">
																												<fo:block>
																													<xsl:copy-of select="$value-of-template_7"/>
																												</fo:block>
																											</xsl:when>
																											<xsl:otherwise>
																												<fo:inline>
																													<xsl:copy-of select="$value-of-template_7"/>
																												</fo:inline>
																											</xsl:otherwise>
																										</xsl:choose>
																									</xsl:for-each>
																								</fo:block>
																							</fo:block-container>
																						</fo:table-cell>
																						<fo:table-cell border-bottom="0.01in solid black" padding="2pt" display-align="center">
																							<fo:block-container overflow="hidden">
																								<fo:block text-align="left"/>
																							</fo:block-container>
																						</fo:table-cell>
																					</fo:table-row>
																					<fo:table-row>
																						<fo:table-cell padding="2pt" display-align="center">
																							<fo:block-container overflow="hidden">
																								<fo:block text-align="left"/>
																							</fo:block-container>
																						</fo:table-cell>
																						<fo:table-cell number-columns-spanned="2" padding="2pt" display-align="center">
																							<fo:block-container overflow="hidden">
																								<fo:block text-align="left"/>
																							</fo:block-container>
																						</fo:table-cell>
																						<fo:table-cell padding="2pt" display-align="center">
																							<fo:block-container overflow="hidden">
																								<fo:block text-align="right"/>
																							</fo:block-container>
																						</fo:table-cell>
																						<fo:table-cell border-right="0.01in solid black" padding="2pt" display-align="center">
																							<fo:block-container overflow="hidden">
																								<fo:block text-align="right"/>
																							</fo:block-container>
																						</fo:table-cell>
																						<fo:table-cell padding="2pt" display-align="center">
																							<fo:block-container overflow="hidden">
																								<fo:block text-align="right"/>
																							</fo:block-container>
																						</fo:table-cell>
																					</fo:table-row>
																					<fo:table-row>
																						<fo:table-cell padding="2pt" display-align="center">
																							<fo:block-container overflow="hidden">
																								<fo:block text-align="left"/>
																							</fo:block-container>
																						</fo:table-cell>
																						<fo:table-cell number-columns-spanned="2" padding="2pt" display-align="center">
																							<fo:block-container overflow="hidden">
																								<fo:block text-align="left"/>
																							</fo:block-container>
																						</fo:table-cell>
																						<fo:table-cell number-columns-spanned="3" padding-right="0.06in" padding="2pt" display-align="center">
																							<fo:block-container overflow="hidden">
																								<fo:block text-align="right">
																									<fo:external-graphic content-width="60%" scaling="non-uniform">
																										<xsl:attribute name="src">
																											<xsl:text>url(</xsl:text>
																											<xsl:call-template name="altova:double-backslash">
																												<xsl:with-param name="text">
																													<xsl:value-of select="string(&apos;cutDown.jpg&apos;)"/>
																												</xsl:with-param>
																												<xsl:with-param name="text-length">
																													<xsl:value-of select="string-length(string(&apos;cutDown.jpg&apos;))"/>
																												</xsl:with-param>
																											</xsl:call-template>
																											<xsl:text>)</xsl:text>
																										</xsl:attribute>
																									</fo:external-graphic>
																									<fo:inline>
																										<xsl:text>&#x200B;</xsl:text>
																									</fo:inline>
																								</fo:block>
																							</fo:block-container>
																						</fo:table-cell>
																					</fo:table-row>
																				</xsl:variable>
																				<xsl:choose>
																					<xsl:when test="string($altova:tablerows)">
																						<xsl:copy-of select="$altova:tablerows"/>
																					</xsl:when>
																					<xsl:otherwise>
																						<fo:table-row>
																							<fo:table-cell>
																								<fo:block/>
																							</fo:table-cell>
																						</fo:table-row>
																					</xsl:otherwise>
																				</xsl:choose>
																			</fo:table-body>
																		</fo:table>
																	</fo:block>
																</fo:block-container>
															</fo:table-cell>
														</fo:table-row>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:variable>
										<xsl:choose>
											<xsl:when test="string($altova:tablerows)">
												<xsl:copy-of select="$altova:tablerows"/>
											</xsl:when>
											<xsl:otherwise>
												<fo:table-row>
													<fo:table-cell>
														<fo:block/>
													</fo:table-cell>
												</fo:table-row>
											</xsl:otherwise>
										</xsl:choose>
									</fo:table-body>
								</fo:table>
							</xsl:if>
						</xsl:for-each>
					</fo:block>
					<fo:block id="SV_RefID_PageTotal"/>
				</fo:flow>
			</fo:page-sequence>
		</fo:root>
	</xsl:template>
	<xsl:template name="altova:double-backslash">
		<xsl:param name="text"/>
		<xsl:param name="text-length"/>
		<xsl:variable name="text-after-bs" select="substring-after($text, '\')"/>
		<xsl:variable name="text-after-bs-length" select="string-length($text-after-bs)"/>
		<xsl:choose>
			<xsl:when test="$text-after-bs-length = 0">
				<xsl:choose>
					<xsl:when test="substring($text, $text-length) = '\'">
						<xsl:value-of select="concat(substring($text,1,$text-length - 1), '\\')"/>
					</xsl:when>
					<xsl:otherwise>
						<xsl:value-of select="$text"/>
					</xsl:otherwise>
				</xsl:choose>
			</xsl:when>
			<xsl:otherwise>
				<xsl:value-of select="concat(substring($text,1,$text-length - $text-after-bs-length - 1), '\\')"/>
				<xsl:call-template name="altova:double-backslash">
					<xsl:with-param name="text" select="$text-after-bs"/>
					<xsl:with-param name="text-length" select="$text-after-bs-length"/>
				</xsl:call-template>
			</xsl:otherwise>
		</xsl:choose>
	</xsl:template>
	<xsl:template name="altova:MakeValueAbsoluteIfPixels">
		<xsl:param name="sValue"/>
		<xsl:variable name="sBeforePx" select="substring-before($sValue, 'px')"/>
		<xsl:choose>
			<xsl:when test="$sBeforePx">
				<xsl:variable name="nLengthOfInteger">
					<xsl:call-template name="altova:GetCharCountOfIntegerAtEndOfString">
						<xsl:with-param name="sText" select="$sBeforePx"/>
					</xsl:call-template>
				</xsl:variable>
				<xsl:variable name="nPosOfInteger" select="string-length($sBeforePx) - $nLengthOfInteger + 1"/>
				<xsl:variable name="nValuePx" select="substring($sBeforePx, $nPosOfInteger)"/>
				<xsl:variable name="nValueIn" select="number($nValuePx) div number($altova:nPxPerIn)"/>
				<xsl:variable name="nLengthBeforeInteger" select="string-length($sBeforePx) - $nLengthOfInteger"/>
				<xsl:variable name="sRest">
					<xsl:call-template name="altova:MakeValueAbsoluteIfPixels">
						<xsl:with-param name="sValue" select="substring-after($sValue, 'px')"/>
					</xsl:call-template>
				</xsl:variable>
				<xsl:value-of select="concat(substring($sBeforePx, 1, $nLengthBeforeInteger), string($nValueIn), 'in', $sRest)"/>
			</xsl:when>
			<xsl:otherwise>
				<xsl:value-of select="$sValue"/>
			</xsl:otherwise>
		</xsl:choose>
	</xsl:template>
	<xsl:template name="altova:GetCharCountOfIntegerAtEndOfString">
		<xsl:param name="sText"/>
		<xsl:variable name="sLen" select="string-length($sText)"/>
		<xsl:variable name="cLast" select="substring($sText, $sLen)"/>
		<xsl:choose>
			<xsl:when test="number($cLast) &gt;= 0 and number($cLast) &lt;= 9">
				<xsl:variable name="nResultOfRest">
					<xsl:call-template name="altova:GetCharCountOfIntegerAtEndOfString">
						<xsl:with-param name="sText" select="substring($sText, 1, $sLen - 1)"/>
					</xsl:call-template>
				</xsl:variable>
				<xsl:value-of select="$nResultOfRest + 1"/>
			</xsl:when>
			<xsl:otherwise>
				<xsl:text>0</xsl:text>
			</xsl:otherwise>
		</xsl:choose>
	</xsl:template>
</xsl:stylesheet>
